### ISSUE TITLE
Allow for unragging arrays in exported models

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#1012]
Right now we allow for unragging `RaggedTensor`s during inference with the `numpy` flag in the `InferenceModel.predict_on_batch` method here:
https://github.com/talmolab/sleap/blob/6cac6519208dbc77a89a1e7fb019fed03d9514ac/sleap/nn/inference.py#L967-L972

It would be desirable to be able to enable this behavior in exported models (e.g., for Bonsai) so that the models always spit out fixed size `tf.Tensor`s (esp. in combination with #1011).

This is doable by:
1. Making a `unrag_outputs: bool = True` as an attribute for `InferenceModel`
2. Checking that attribute in the snippet above and unragging accordingly (maybe without converting to numpy?)
3. Expose it in the higher level model export functions as a keyword + CLI arg

**Comment by roomrys** [comment]
This feature is now available in the (pre) release 1.3.0a0, to install, first [uninstall](https://sleap.ai/installation.html#upgrading-and-uninstalling) and then:
**`conda` (Windows/Linux/GPU)**:
```
conda create -y -n sleap -c sleap -c sleap/label/dev -c nvidia -c conda-forge sleap=1.3.0a0
```
**`pip` (any OS except Apple Silicon)**:
```
pip install sleap==1.3.0a0
```

**Warning:** This is a pre-release! Expect bugs and strange behavior when testing.
