### ISSUE TITLE
GUI bug: dragging a node is glitchy (on Windows 11?)

### ISSUE THREAD

**Issue by olinesn** [talmolab/sleap#1019]
# Bug description

This bug showed up in 1.2.7 and 1.2.8, but I've tested 1.2.6 and earlier and it is absent in those versions. When editing inferred skeletons, changing the position of a node results in a 'flicker' where the node returns to its original position, and then switches back to the cursor. If the user lets go of the left mouse button while dragging the node, after the flicker has started but before the node has returned to the cursor, the node is left in its original position, but the text color has changed from red to teal. This may result in a user thinking that the node correction has registered, when it has not.

## Expected behaviour

When editing an inferred (red text) node position by selecting it with a mouse and dragging it to a new position, the node would track smoothly with the mouse cursor.

## Actual behaviour

When editing an inferred (red text) node position by selecting it with a mouse and dragging it to a new position, after ~0.25 seconds, the node flickers back to its original position, and then returns to the cursor. This does _not_ happen for greyed-out nodes.

## Your personal set up

- OS: Win 11

- Version(s): 1.2.8, 1.2.7 (the bug does not exist on 1.2.6, tested)

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [x] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [M1 Macs](https://sleap.ai/installation.html#m1-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```

</details>

## Screenshots

See attached video

https://user-images.githubusercontent.com/69451171/199030925-cade6752-d5fe-47d8-8edd-7d8dec4de1d3.mp4

## How to reproduce

1. Run inference on a set of suggested frames with a trained model.
2. Double-click on a node inside an inferred skeleton.
3. Drag said node to a new XY position.

**Comment by olinesn** [comment]
I'm actually seeing this bug in 1.2.6 as well

**Comment by olinesn** [comment]
Since I'm seeing this in 1.2.6 on computers that I previously did not, I'm wondering if this is a Windows 11 bug. I'll try to test it out on a different computer that's on Win10. If I don't get it, then I'll upgrade the PC to Win11 and test again. If I then see the bug, we'll know it's Win11.

**Comment by talmo** [comment]
This bug is a bit older. I don't think we still have it in newer versions, but let me know if so.

**Comment by olinesn** [comment]
Actually it happened to me the other day! You can replicate it by dragging
and holding a node, and then changing frame while you're still holding onto
the node. When you let go of left click, the node snaps to the top left
corner.

I've mostly learned to not do that, but it prevents input queuing, so it's
a (mild) inconvenience.

**Comment by olinesn** [comment]
I just checked to confirm, and it looks like it's happening when I'm
holding a node and then press the GO TO NEXT LABELED FRAME key
