### ISSUE TITLE
sleap-export incorrectly accesses `args` resulting in error

### ISSUE THREAD

**Issue by diogoflduarte** [talmolab/sleap#1031]
Hi!

I'm trying to export a model to a .pb file for later use in bonsai rx.

current directory is the "models" under my current project,

if I run 
`sleap-export --model r"221107_203914.single_instance.n=142"`

I get the following output:
`Traceback (most recent call last):
  File "C:\Miniconda3\envs\sleap\Scripts\sleap-export-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.2.8', 'console_scripts', 'sleap-export')())
  File "C:\Miniconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 4241, in export_cli
    export_model(args["models"], args["export_path"])
TypeError: 'Namespace' object is not subscriptable`

Running on Windows with SLEAP v1.2.8 

If this is misinterpretation of input arguments on my behalf, I'll delete the issue and move to "help" with the corresponding solution.

Thanks!

**Comment by roomrys** [comment]
Hi @diogoflduarte,

Just tried out the command on my end. Have you tried without the `r"..."`, i.e.
```
sleap-export --model 221107_203914.single_instance.n=142
```

Let me know if that helps for you (it worked for me - there might be something else going on though).

Thanks,
Liezl

**Comment by roomrys** [comment]
Hi @diogoflduarte,

Just took another look at your error message and the current source code. It seems that we pushed a fix for your problem #962, but it is only available in the source code right now. You can wait until our next release - which should be very soon - or [install sleap from source](https://sleap.ai/installation.html#conda-from-source) to get the fix asap.

Thanks,
Liezl

**Comment by diogoflduarte** [comment]
Confirmed that @roomrys  solution works
