### ISSUE TITLE
Skeleton templates

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#1106]
# Problem background
- Defining the skeleton is an often confusing first step when starting a project.
- There are many [best practices for skeleton design](https://sleap.ai/guides/skeletons.html) that are dependent on the specifics of the dataset and model type that will be used.
- Users defining their own skeletons contributes to the lack of standardization across labeling projects, making it harder to reuse and unify labeled data that have different skeleton definitions (see for example, [this creative approach](https://openaccess.thecvf.com/content/WACV2023/papers/Sarandi_Learning_3D_Human_Pose_Estimation_From_Dozens_of_Datasets_Using_WACV_2023_paper.pdf) to dealing with this).

# Feature proposal
- We have a number of skeletons that we've used for a variety of species and conditions, so let's make them readily available in the GUI so users can just pick from the list instead of having to define their own.
- Adding a basic visualization will help with UX (like we had in the [original LEAP GUI](https://github.com/talmo/leap/wiki/Tutorial:-Training-LEAP-from-scratch#creating-a-skeleton)).

# Implementation details
## PR 1: Base functionality (MVP)
1. Add the skeletons from the [reference datasets](https://sleap.ai/datasets.html) in the SLEAP paper.
    - SLEAP `Skeleton`s can be serialized to JSON files when you click **Save** from the skeleton pane in the GUI or via [`Skeleton.save_json()`](https://sleap.ai/api/sleap.skeleton.html#sleap.skeleton.Skeleton.save_json).
    - Download one of the SLP files from each of the [reference datasets](https://sleap.ai/datasets.html) and extract their skeleton. Name them by the dataset name (e.g., `flies13`, `mice_hc`, etc.).
    - Rename the skeleton to the dataset name within the JSON file (i.e., set the `Skeleton.name` attribute).
    - Add the JSON files to a new folder `sleap/sleap/skeletons` (analogous to [`sleap/sleap/training_profiles`](https://github.com/talmolab/sleap/tree/develop/sleap/training_profiles)).
    
2. The Skeleton JSONs can be auto-discovered following a similar pattern to how we do it for training profiles:
    ```py
    # Get local path to the training profiles (this may be different on different systems depending on how SLEAP is installed).
    profiles_folder = sleap.utils.get_package_file("sleap/training_profiles")
    
    # Search for JSON files within this folder and return them in a list.
    json_files = sleap.utils.find_files_by_suffix(profiles_folder, suffix=".json", depth=1)
    ```
    Alternatively, the paths can just be hardcoded since we won't be adding new skeletons all the time.

3. Add a GUI dropdown in the Skeleton panel for selecting and loading the built-in skeleton.
    - The code that defines the Skeleton panel elements is here:
    https://github.com/talmolab/sleap/blob/c4861e3a18d39635f1214f3bc9c46415557c861f/sleap/gui/app.py#L993-L1067
    This is where a dropdown should be added.
    - Use a [`QComboBox`](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QComboBox.html) to define the dropdown.
    - Populate the dropdown with step 2 above, but have it default to a blank item.
    - Modify the **Load** button functionality in the skeleton panel GUI to load from the list if the non-blank item is selected.
    - *Optional*: Play with the layout and possibly add text ([`QLabel`](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QLabel.html)) elements to make it clear to the user.

## PR 2: Preview
Once the core functionality is implemented, add a couple of UI elements which will help with the UX. A plain dropdown with no information other than the filename is not very descriptive, so new users may not know which skeleton to select. One way to deal with this is to add two additional elements to the skeleton: a text description and a preview image.

1. Modify the [`Skeleton`](https://github.com/talmolab/sleap/blob/c4861e3a18d39635f1214f3bc9c46415557c861f/sleap/skeleton.py#L88) class to also contain two optional fields:
    ```py
    class Skeleton:
        # ...
        preview_image: Optional[bytes] = None
        description: Optional[str] = None
    ```

2. Make sure that serialization/deserialization is handled properly in [`Skeleton.to_json()`](https://github.com/talmolab/sleap/blob/c4861e3a18d39635f1214f3bc9c46415557c861f/sleap/skeleton.py#L955-L983) and [`Skeleton.from_json()`](https://github.com/talmolab/sleap/blob/c4861e3a18d39635f1214f3bc9c46415557c861f/sleap/skeleton.py#L1012-L1039)
    - The JSON serializer might handle byte strings just fine, but we should also check for backwards compatibility with older skeletons that will not have this field.

3. Add images to the built in skeletons.
    - This can just be screenshots that you take from the GUI after loading the reference datasets. They should have node label names visible.
    - Encode the screenshots as byte strings so they can be stored in the JSON file in the `preview_image` field. This can be done as such:
    ```py
    import base64
    from io import BytesIO
    from PIL import Image
    
    img = Image.open("test.png")
    img_stream = BytesIO()
    img.save(img_stream, format="PNG")  # encode the image as PNG (TODO: compress/resize)
    img_bytes = img_stream.getvalue()  # image in binary format
    img_b64 = base64.b64encode(img_bytes)  # bytes
    ```
    - This is basically a thumbnail and should be <<5 KB.
    - Make sure the bytestring is as small as possible, so explore different resolutions, lossy compression values or maybe just use JPEG instead of PNG to encode the image.
    - Do this once per skeleton.
    - Optionally add the serialization code above in `sleap.utils` for future use.

4. Implement image decoding from base64 strings so we can convert them back into images we can display in the GUI:
    ```py
    import base64
    from io import BytesIO
    from PIL import Image
    import numpy as np
    
    img_b64 = skeleton.preview_image  # this should be stored in the file originally
    img = Image.open(BytesIO(base64.b64decode(img_b64)))  # decode the image into a PIL.Image
    # np.array(img)   # convert it into a (height, width, channels) uint8 array
    # img.toqimage()  # convert it into a QImage for display in Qt
    # img.toqpixmap()  # convert it into a QPixmap for display in Qt
    ```
    This is basically the inverse of step 3.

5. Add the preview and description elements to the Skeleton panel in the GUI.
    - These should be fetched from the JSON files by loading the skeleton when the user selects one from the dropdown.
    - The description can be displayed using a [`QLabel`](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QLabel.html).
    - The image display is a little trickier. It probably is best rendered via a [`QPixmap`](https://doc.qt.io/qtforpython-5/PySide2/QtGui/QPixmap.html#PySide2.QtGui.PySide2.QtGui.QPixmap). Search the SLEAP code for how we use it in other places for examples.

**Comment by roomrys** [comment]
This feature is now available in the (pre) release 1.3.0a0, to install, first [uninstall](https://sleap.ai/installation.html#upgrading-and-uninstalling) and then:
**`conda` (Windows/Linux/GPU)**:
```
conda create -y -n sleap -c sleap -c sleap/label/dev -c nvidia -c conda-forge sleap=1.3.0a0
```
**`pip` (any OS except Apple Silicon)**:
```
pip install sleap==1.3.0a0
```

**Warning:** This is a pre-release! Expect bugs and strange behavior when testing.
