### ISSUE TITLE
Entering the symmetric skeleton node in skeleton table not working (v.1.2.9)

### ISSUE THREAD

**Issue by sommerc** [talmolab/sleap#1135]
# Bug description

When entering symmetry in the skeleton node editor by entering the symmetric node into the *Symmetry* column an exception is raised:

```
Traceback (most recent call last):
  File "C:\Miniconda\envs\sleap\lib\site-packages\sleap\gui\dataviews.py", line 158, in setData
    if item_value == value:
UnboundLocalError: local variable 'item_value' referenced before assignment
```
- OS:
Windows 10
- Version(s):
SLEAP v1.2.9

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [x] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [M1 Macs](https://sleap.ai/installation.html#m1-macs)

**Comment by roomrys** [comment]
This feature is now available in the (pre) release 1.3.0a0, to install, first [uninstall](https://sleap.ai/installation.html#upgrading-and-uninstalling) and then:
**`conda` (Windows/Linux/GPU)**:
```
conda create -y -n sleap -c sleap -c sleap/label/dev -c nvidia -c conda-forge sleap=1.3.0a0
```
**`pip` (any OS except Apple Silicon)**:
```
pip install sleap==1.3.0a0
```

**Warning:** This is a pre-release! Expect bugs and strange behavior when testing.
