### ISSUE TITLE
Unable to load frame while inferenceing 

### ISSUE THREAD

**Issue by sridutt07** [talmolab/sleap#1153]
I am new to SLEAP and while following the Colab document, 

Running the code : 
```
!sleap-track Controled_env.mp4 \
    --frames 0-200 \
    --tracking.tracker simple \
    -m models/230125_155141.single_instance
```

I get the following error:

INFO:numexpr.utils:NumExpr defaulting to 2 threads.
Started inference at: 2023-01-26 01:12:25.816690
Args:
{
│   'data_path': 'Controled_env.mp4',
│   'models': ['models/230125_155141.single_instance'],
│   'frames': '0-200',
│   'only_labeled_frames': False,
│   'only_suggested_frames': False,
│   'output': None,
│   'no_empty_frames': False,
│   'verbosity': 'rich',
│   'video.dataset': None,
│   'video.input_format': 'channels_last',
│   'video.index': '',
│   'cpu': False,
│   'first_gpu': False,
│   'last_gpu': False,
│   'gpu': 'auto',
│   'max_edge_length_ratio': 0.25,
│   'dist_penalty_weight': 1.0,
│   'batch_size': 4,
│   'open_in_gui': False,
│   'peak_threshold': 0.2,
│   'tracking.tracker': 'simple',
│   'tracking.target_instance_count': None,
│   'tracking.pre_cull_to_target': None,
│   'tracking.pre_cull_iou_threshold': None,
│   'tracking.post_connect_single_breaks': None,
│   'tracking.clean_instance_count': None,
│   'tracking.clean_iou_threshold': None,
│   'tracking.similarity': None,
│   'tracking.match': None,
│   'tracking.track_window': None,
│   'tracking.min_new_track_points': None,
│   'tracking.min_match_points': None,
│   'tracking.img_scale': None,
│   'tracking.of_window_size': None,
│   'tracking.of_max_levels': None,
│   'tracking.save_shifted_instances': None,
│   'tracking.kf_node_indices': None,
│   'tracking.kf_init_frame_count': None
}

INFO:sleap.nn.inference:Auto-selected GPU 0 with 15106 MiB of free memory.
Versions:
SLEAP: 1.2.9
TensorFlow: 2.8.4
Numpy: 1.21.6
Python: 3.8.10
OS: Linux-5.10.147+-x86_64-with-glibc2.29

System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True

Video: Controled_env.mp4
Predicting... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ETA: -:--:-- ?
Traceback (most recent call last):
  File "/usr/local/bin/sleap-track", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/sleap/nn/inference.py", line 4660, in main
    labels_pr = predictor.predict(provider)
  File "/usr/local/lib/python3.8/dist-packages/sleap/nn/inference.py", line 440, in predict
    self._make_labeled_frames_from_generator(generator, data)
  File "/usr/local/lib/python3.8/dist-packages/sleap/nn/inference.py", line 1425, in _make_labeled_frames_from_generator
    for ex in generator:
  File "/usr/local/lib/python3.8/dist-packages/sleap/nn/inference.py", line 349, in _predict_generator
    for ex in self.pipeline.make_dataset():
  File "/usr/local/lib/python3.8/dist-packages/sleap/nn/data/pipelines.py", line 282, in make_dataset
    ds = self.providers[0].make_dataset()
  File "/usr/local/lib/python3.8/dist-packages/sleap/nn/data/providers.py", line 398, in make_dataset
    self.video.get_frame(self.video.last_frame_idx)
  File "/usr/local/lib/python3.8/dist-packages/sleap/io/video.py", line 1087, in get_frame
    return self.backend.get_frame(idx)
  File "/usr/local/lib/python3.8/dist-packages/sleap/io/video.py", line 492, in get_frame
    raise KeyError(f"Unable to load frame {idx} from {self}.")
KeyError: "Unable to load frame 14007 from MediaVideo(filename='Controled_env.mp4', grayscale=True, bgr=True, dataset='', input_format='channels_last')."

**Comment by talmo** [comment]
Hi @sridutt07,

This is most likely due to the video not being in a seekable format. [Check out this section of our help page](https://sleap.ai/help.html#does-my-data-need-to-be-in-a-particular-format) and let us know if re-encoding doesn't solve the problem for you.

Cheers,

Talmo

**Comment by sridutt07** [comment]
Thank you , that fixed the issue
