### ISSUE TITLE
KeyError issue training single instance using google colab

### ISSUE THREAD

**Issue by mjin1812** [talmolab/sleap#1216]
# Bug description
For some reason, a "nodes" KeyError pops up whenever I try to run training on colab using a single animal pipeline.

I've been following the online tutorial for training and inference on my own 
[data](https://drive.google.com/drive/folders/1X8aSs9cYvDjfbEWzJT1wu0sovNl7tC3b?usp=sharing). I labelled only ~40 frames to test the ability to train on colab. When try to train using the command `!sleap-train single_instance.json colabDemo.slp` I get a KeyError. I've attached the full error in a text file.

## Expected behaviour

Training 

## Actual behaviour

KeyError: 'nodes'

## Your personal set up

Error was from using the demo colab notebook. 

But here is my local computer setup in case it's relevant.
Software versions:
SLEAP: 1.3.0a0
TensorFlow: 2.8.4
Numpy: 1.21.5
Python: 3.7.16
OS: Windows-10-10.0.19041-SP0

Installation was from miniconda

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```
Again this is for my local setup. Not sure if it's relevant.
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
accessible-pygments       0.0.3                    pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
beautifulsoup4            4.11.2                   pypi_0    pypi
black                     21.6b0                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
ca-certificates           2023.01.10           haa95532_0
cached-property           1.5.2                      py_0
cachetools                5.3.0                    pypi_0    pypi
cattrs                    1.1.1                    pypi_0    pypi
certifi                   2021.10.8                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
cfgv                      3.3.1                    pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
coverage                  7.2.1                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.6                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
efficientnet              1.0.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
exceptiongroup            1.1.0                    pypi_0    pypi
ffmpeg                    4.2.2                he774522_0
filelock                  3.9.0                    pypi_0    pypi
flatbuffers               23.3.3                   pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.10.4               hd328e21_0
gast                      0.5.3                    pypi_0    pypi
geos                      3.8.0                h33f27b4_0
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
google-auth               2.16.2                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
greenlet                  2.0.2                    pypi_0    pypi
grpcio                    1.51.3                   pypi_0    pypi
h5py                      3.1.0           nompi_py37h19fda09_100    conda-forge
hdf5                      1.10.6               h1756f20_1
hdmf                      3.5.1                    pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2
icu                       69.1                 h0e60522_0    conda-forge
identify                  2.5.19                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
image-classifiers         1.0.0                    pypi_0    pypi
imageio                   2.15.0                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
imgstore                  0.2.9                    pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2023.0.0         h59b6b97_25923
ipykernel                 6.16.2                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.3                    pypi_0    pypi
jaraco-classes            3.2.3                    pypi_0    pypi
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.17.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_1
jsmin                     3.0.1                    pypi_0    pypi
json5                     0.9.11                   pypi_0    pypi
jsonpickle                1.2                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter-cache             0.4.3                    pypi_0    pypi
jupyter-client            7.4.9                    pypi_0    pypi
jupyter-core              4.12.0                   pypi_0    pypi
jupyter-server            1.13.5                   pypi_0    pypi
jupyter-server-mathjax    0.2.6                    pypi_0    pypi
jupyter-sphinx            0.3.2                    pypi_0    pypi
jupyterlab                3.3.4                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.16.3                   pypi_0    pypi
jupyterlab-widgets        1.1.2                    pypi_0    pypi
keras                     2.8.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   23.13.1                  pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lcms2                     2.12                 h83e58a3_0
lerc                      3.0                  hd77b12b_0
libblas                   3.8.0                    20_mkl    conda-forge
libcblas                  3.8.0                    20_mkl    conda-forge
libclang                  15.0.6.1                 pypi_0    pypi
libdeflate                1.8                  h2bbff1b_5
libiconv                  1.16                 h2bbff1b_2
liblapack                 3.8.0                    20_mkl    conda-forge
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.3.0                hd413186_2    conda-forge
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
libzlib                   1.2.12               h8ffe710_2    conda-forge
linkify-it-py             2.0.0                    pypi_0    pypi
livereload                2.6.3                    pypi_0    pypi
lxml                      4.9.2                    pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.4.1                    pypi_0    pypi
markdown-it-py            1.1.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mdit-py-plugins           0.2.8                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2020.2                      256
more-itertools            9.1.0                    pypi_0    pypi
msys2-conda-epoch         20160418                      1
mypy-extensions           1.0.0                    pypi_0    pypi
myst-nb                   0.13.2                   pypi_0    pypi
myst-parser               0.15.2                   pypi_0    pypi
nbclassic                 0.5.3                    pypi_0    pypi
nbclient                  0.5.13                   pypi_0    pypi
nbconvert                 6.5.4                    pypi_0    pypi
nbdime                    3.1.1                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
ndx-pose                  0.1.1                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
nixio                     1.5.3                    pypi_0    pypi
nodeenv                   1.7.0                    pypi_0    pypi
notebook                  6.5.3                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numpy                     1.21.5           py37h2830a78_1    conda-forge
oauthlib                  3.2.2                    pypi_0    pypi
olefile                   0.46                     py37_0
opencv-python             4.5.5.64                 pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0
openssl                   1.1.1t               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 22.0             py37haa95532_0
pandas                    1.3.5            py37h9386db6_0    conda-forge
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pathspec                  0.11.0                   pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.4.0            py37hd7d9ad0_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.9.6                    pypi_0    pypi
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              3.1.0                    pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
pre-commit                2.21.0                   pypi_0    pypi
prometheus-client         0.16.0                   pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydata-sphinx-theme       0.13.1                   pypi_0    pypi
pygithub                  1.58.0                   pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pyjwt                     2.6.0                    pypi_0    pypi
pykalman                  0.9.5                    pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pynwb                     2.3.1                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyreadline                2.1                      py37_1
pyrsistent                0.19.3                   pypi_0    pypi
pyside2                   5.14.1                   pypi_0    pypi
pytest                    7.2.2                    pypi_0    pypi
pytest-cov                3.0.0                    pypi_0    pypi
pytest-qt                 4.2.0                    pypi_0    pypi
pytest-xvfb               2.0.0                    pypi_0    pypi
python                    3.7.16               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-rapidjson          1.9                      pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2022.7           py37haa95532_0
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pyvirtualdisplay          3.0                      pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   305                      pypi_0    pypi
pywin32-ctypes            0.2.0                    pypi_0    pypi
pywinpty                  1.1.6                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.0.0                   pypi_0    pypi
qimage2ndarray            1.10.0                   pypi_0    pypi
qt                        5.12.9               h556501e_6    conda-forge
qtpy                      2.2.0            py37haa95532_0
readme-renderer           37.3                     pypi_0    pypi
regex                     2022.10.31               pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
requests-toolbelt         0.10.1                   pypi_0    pypi
rfc3986                   2.0.0                    pypi_0    pypi
rich                      10.16.1                  pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.7.3            py37hb6553fb_0    conda-forge
seaborn                   0.12.2                   pypi_0    pypi
segmentation-models       1.0.1                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                58.0.4           py37haa95532_0
shapely                   1.7.1            py37h06580b3_0
shiboken2                 5.14.1                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
sleap                     1.3.0a0                   dev_0    <develop>
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.4                      pypi_0    pypi
sphinx                    4.5.0                    pypi_0    pypi
sphinx-autobuild          2021.3.14                pypi_0    pypi
sphinx-book-theme         1.0.0                    pypi_0    pypi
sphinx-copybutton         0.5.1                    pypi_0    pypi
sphinx-togglebutton       0.3.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                1.4.46                   pypi_0    pypi
sqlite                    3.40.1               h2bbff1b_0
tensorboard               2.8.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.8.4                    pypi_0    pypi
tensorflow-estimator      2.8.0                    pypi_0    pypi
tensorflow-hub            0.12.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
termcolor                 2.2.0                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
twine                     3.3.0                    pypi_0    pypi
typed-ast                 1.5.4                    pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2022.7                   pypi_0    pypi
tzlocal                   4.2                      pypi_0    pypi
uc-micro-py               1.0.1                    pypi_0    pypi
urllib3                   1.26.14                  pypi_0    pypi
vc                        14.2                 h21ff451_1
virtualenv                20.20.0                  pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.6                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py37haa95532_0
widgetsnbextension        3.6.2                    pypi_0    pypi
wincertstore              0.2              py37haa95532_2
wrapt                     1.15.0                   pypi_0    pypi
xz                        5.2.10               h8cc25b3_1
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.12               h8cc25b3_2
zstd                      1.5.2                h19a0ad4_0

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```

</details>

## How to reproduce

1) Following the example colab notebook.
2) Running on the demo labelled .slp file and training package I generated (should be linked)

[SleapDemoColabError.txt](https://github.com/talmolab/sleap/files/10937094/SleapDemoColabError.txt)

**Comment by aereimer** [comment]
Maybe related with this, I am trying the version 1.3.0a0 and after opening (and saving) a slp file with the new version, I am unable to open it with previous versions (1.2.9, 1.2.6, 1.2.2). It still opens with 1.3.0a0, but with other versions I get the KeyError: 'nodes' too.

**Comment by mjin1812** [comment]
The previous comment helped me solve this issue! I checked the version of sleap automatically downloaded on colab and it was 1.2.8. I forced an installation of the same version as my local computer with `!pip install -v 'sleap==1.3.0a0' and now I can train!

**Comment by roomrys** [comment]
Related issue: #1217
Related PR: #1222
