### ISSUE TITLE
How should I export the model to onnx?

### ISSUE THREAD

**Issue by lyylsh** [talmolab/sleap#1228]
How should I export the model to onnx? If it is possible to deploy to edge devices.
Thanks.

**Comment by talmo** [comment]
Hi @lyylsh,

We haven't tried ONNX export directly, but an intermediate step you could make use of is the [`sleap-export` CLI](https://sleap.ai/guides/cli.html#sleap-export) which can produce a TensorFlow frozen graph with all of the inference ops for some model types which you you can then convert to ONNX.

Let us know how that goes or if we can help with troubleshooting!

Cheers,

Talmo

**Comment by lyylsh** [comment]
> Hi @lyylsh,
> 
> We haven't tried ONNX export directly, but an intermediate step you could make use of is the [`sleap-export` CLI](https://sleap.ai/guides/cli.html#sleap-export) which can produce a TensorFlow frozen graph with all of the inference ops for some model types which you you can then convert to ONNX.
> 
> Let us know how that goes or if we can help with troubleshooting!
> 
> Cheers,
> 
> Talmo

Thanks. I will try that. Thanks a lot.

**Comment by lyylsh** [comment]
> Hi @lyylsh,
> 
> We haven't tried ONNX export directly, but an intermediate step you could make use of is the [`sleap-export` CLI](https://sleap.ai/guides/cli.html#sleap-export) which can produce a TensorFlow frozen graph with all of the inference ops for some model types which you you can then convert to ONNX.
> 
> Let us know how that goes or if we can help with troubleshooting!
> 
> Cheers,
> 
> Talmo

Hi @Talmo,
I'm trying to convert h5 model to TensorFlow frozen graph and then to onnx model, but I've encountered some problems in it and would like to ask you for advice.

The input and output information of the pb model looks like this : 
<img width="654" alt="2023-03-31" src="https://user-images.githubusercontent.com/120197865/229015461-bcc58599-9421-408e-aeb6-dad9e241b2ee.png">

I tried using the
 'python -m tf2onnx.convert --input saved_model.pb --output model.onnx  
--outputs Identity:0,Identity_1:0,Identity_2:0,Identity_3:0,Identity_4:0,Identity_5:0,Identity_6:0,Identity_7:0 
--inputs x:0 --inputs-as-nchw x:0 --opset 12' 
command to try to convert to the onnx model.

The model structure of onnx as seen in netron looks like this:
<img width="947" alt="2023-03-31 (2)" src="https://user-images.githubusercontent.com/120197865/229016163-762ae179-3248-4281-8111-07c9adc31ccd.png">

When I try to read in the onnx model the following error is reported:
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from D:\exported_model\model.onnx failed:This is an invalid model. In Node, ("StatefulPartitionedCall/StatefulPartitionedCall/top_down_inference_model_1/centroid_crop_1/StatefulPartitionedCall/PartitionedCall_1/Dilation2D", Dilation2D, "", -1) : ("StatefulPartitionedCall/StatefulPartitionedCall/top_down_inference_model_1/centroid_crop_1/StatefulPartitionedCall/PartitionedCall_1/Reshape_1:0": tensor(float),"StatefulPartitionedCall/StatefulPartitionedCall/top_down_inference_model_1/centroid_crop_1/StatefulPartitionedCall/PartitionedCall_1/Reshape:0": tensor(float),) -> ("StatefulPartitionedCall/StatefulPartitionedCall/top_down_inference_model_1/centroid_crop_1/StatefulPartitionedCall/PartitionedCall_1/Dilation2D:0",) , Error No Op registered for Dilation2D with domain_version of 12

It doesn't look like it's working properly.

Thanks!

**Comment by talmo** [comment]
Hi @lyylsh,

Not sure if you ever got this working but it's likely that ONNX doesn't support our peak finding operations (dilation with custom kernel). This might just not be possible until that's the case, but we'll revisit it once we implement our new neural network backend which will totally change the model format.

Feel free to open another issue if you're still having problems!

Talmo
