### ISSUE TITLE
Instances disappear after "File > Export Analysis H5"

### ISSUE THREAD

**Issue by isabelperezf** [talmolab/sleap#1235]
# Instances disappear after "File > Export Analysis H5"

I´ve been using SLEAP to label, train and inference with frames extracted from different videos. Then, when I got a good model I did the prediction and track (locally) with this model in one simple video. Finally, I saved the project and I did File > Export Analysis H5 >current video and I obtained a . h5 document. The problem is that when I later re-opened the project.slp (the one in which I did the prediction and track), it was empty apart from the skeleton. Is this supposed to be the correct behavior? 
@auesro

- OS:
Windows 11
- Version(s): [SLEAP v1.2.8, python 3.7]

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [x ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

**Comment by roomrys** [comment]
Hi @isabelperezf,

This is not the correct behavior - this is very concerning behavior. Are you able to reproduce this (after you re-predict or on an older copy of the slp)?

Thanks,
Liezl

**Comment by isabelperezf** [comment]
Hi, I repeated the same thing, but in different video and I everthing was fine, I obtained a .slp with all the predictions and a correct .h5 document. But...any idea what could have happened with the previous .slp? Thank u a lot.

**Comment by isabelperezf** [comment]
Hi, I repeated the same thing, but in different video and I everthing was fine, I obtained a .slp with all the predictions and a correct .h5 document. But...any idea what could have happened with the previous .slp? Thank u a lot.
