### ISSUE TITLE
Removing videos from a project doesn't update Labeled frames: YYY in project

### ISSUE THREAD

**Issue by olinesn** [talmolab/sleap#1261]
# Bug description

When I have a project with a large number of videos and many labelled frames for each video, and want to break out a section to build a new project on a smaller subset of those videos, I save the project "as", and then remove videos. However the "Labeled Frames: XX in video, YYY in project," Y values do not update.

## Expected behaviour

Y values would recalculate when videos are removed from a project.

## Actual behaviour

Y values are never updated to remove old labeled frames, but do change when new frames are added.

## Your personal set up

- OS:
Windows 11
- Version(s):
SLEAP v1.2.9
- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] 
<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```

</details>

## How to reproduce

Build a project with 7 videos, label 2 frames in each video. GUI will show "Labeled frames: 2 in video, 14 in project." Then remove 1 video. GUI will still show "Labeled frames: 2 in video, 14 in project," even though there are now only 12 in the project.

**Comment by roomrys** [comment]
This should be addressed in [SLEAP 1.3.2](https://github.com/talmolab/sleap/releases/tag/v1.3.2).
