### ISSUE TITLE
Recommended installation on MacOS not working

### ISSUE THREAD

**Issue by bentaculum** [talmolab/sleap#1367]
# Bug description

The proposed install command (with addition of `python=3.8`, as suggested [here](https://sleap.ai/develop/installation.html#apple-silicon-macs-pre-installation)):
```
mamba create -y -n sleap -c conda-forge -c anaconda -c sleap sleap=1.3.1 python=3.8
```
fails for me with the following error msg:

```
Looking for: ['sleap', 'python=3.8', 'pip', 'ipython', 'ipdb', 'matplotlib', 'numpy', 'line_profiler', 'autopep8', 'flake8', 'pylint', 'pynvim']

anaconda/osx-arm64                                            No change
anaconda/noarch                                               No change
conda-forge/osx-arm64                                         No change
pkgs/main/osx-arm64                                           No change
pkgs/main/noarch                                              No change
sleap/osx-arm64                                               No change
pkgs/r/noarch                                                 No change
sleap/noarch                                                  No change
pkgs/r/osx-arm64                                              No change
conda-forge/noarch                                  13.1MB @   2.1MB/s  6.4s
Could not solve for environment specs
The following package could not be installed
└─ sleap   does not exist (perhaps a typo or a missing channel).
```

- OS: macOS 12.6.1
- mamba: 1.4.4

What am I missing? The `-c sleap` option is there to direct to the correct conda channel, so not sure why this fails.

**Comment by roomrys** [comment]
Hi @bentaculum,

You've found the way to our development docs (not the `/develop` in the url).

SLEAP 1.3.1 is not on the main sleap channel yet, but can be found on the dev channel:
```
mamba create -y -n sleap -c conda-forge -c anaconda -c sleap/label/dev -c sleap sleap=1.3.1
```

We only have builds for python 3.9 for the macs though, so I don't believe it will work for python 3.8...

Let me know how that goes please! (If you decide python 3.9 is fine?)

Thanks,
Liezl

**Comment by roomrys** [comment]
Hi @bentaculum,

SLEAP 1.3.1 has been released! After [the build](https://github.com/talmolab/sleap/actions/runs/5426857405) finishes, the conda packages will be uploaded and ready for download. I am closing this issue, but let me know if it remains a problem.

Thanks,
Liezl
