### ISSUE TITLE
Remove Videos in Batch

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#1375]
### Discussed in https://github.com/talmolab/sleap/discussions/1363

<div type='discussions-op-text'>

<sup>Originally posted by **daskandalis** June 23, 2023</sup>
Currently videos have to be removed one at a time. Videos can be added in a batch, it would be helpful to have a function to remove them in a batch as well.</div>

**Comment by roomrys** [comment]
This should be addressed in [SLEAP 1.3.2](https://github.com/talmolab/sleap/releases/tag/v1.3.2).
