### ISSUE TITLE
Simplify Mac install dependencies 

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#1379]
Right now we use `wget` to download mambaforge, but this doesn't come natively in OS X, requiring `brew` to install, which in turn requires Xcode.

Altogether it's a 5 step install (Xcode, brew, wget, mamba, sleep) as opposed to 2 steps on other OSes. It also requires 2 terminal restarts, which is super confusing for users who never use it.

I think `curl` might be bundled with OS X, so if mamba works without Xcode, this would drastically reduce the complexity of installation on Macs.

**Comment by roomrys** [comment]
We updated the docs for the apple silicon in [1.3.2](https://github.com/talmolab/sleap/commit/bbc43c1f9024a14dfd5bbb797414214897ab3631#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56) (which we had resources to test the command), but kept the command as is for Pre-M1 macs.
