### ISSUE TITLE
Exporting labeled frames in JSON 

### ISSUE THREAD

**Issue by AdwaitMD** [talmolab/sleap#1409]
# Bug description

'Export Labels Package' is not working when I tried to save in JSON format
## Expected behaviour

JSON or JSON.zip files is saved 
## Actual behaviour

Nothing happens and I get follwoing error "TypeError: write() got an unexpected keyword argument 'all_labeled'"
## Your personal set up

- OS:
Windows 11 - 

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [x] [Conda from package](https://sleap.ai/installation.html#conda-package)
 

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
TypeError: write() got an unexpected keyword argument 'all_labeled'
</details>

**Comment by roomrys** [comment]
This should now be addressed in the latest release SLEAP 1.3.2.
