### ISSUE TITLE
Error when running training: 'Type Error: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by juliagorman** [talmolab/sleap#1429]
Hello, I have been trying to train a model that comprises of labels from several different videos. I exported those labels as a sleep package and then merged them into one project. Once I had all these labels I went to train the model it never started running citing an error in the command line terminal. I checked the terminal but didn't understand what the issue was exactly, as I have done this exact thing many times before but today tried doing this with two different projects and both times got the same error. 

I am running SLEAP v1.2.9 

![Screenshot 2023-07-28 at 6 19 48 PM](https://github.com/talmolab/sleap/assets/32439305/795e3d2d-d63e-4216-9ec8-c083dc00375d)

**Comment by roomrys** [comment]
Hi @juliagorman,

Can you try merging the projects before exporting to a pkg.slp?

Thanks,
Liezl

P.S. I found two issues which were similar, but not quite the same... #1139 Is you pkg.slp in a zipped folder? #1014 Is your data on a different drive than where you are running SLEAP?
