### ISSUE TITLE
matched_instance_distances in sleap.info.metrics does not have default matching function

### ISSUE THREAD

**Issue by eringiglio** [talmolab/sleap#1517]
What it says on the tin: I'd like to use [sleap.info.metrics.matched_instance_distances](https://github.com/talmolab/sleap/blob/41001532601b1190342dc37cd8e2a94a000a2f0c/sleap/info/metrics.py#L16) in a routine I'm writing to identify low quality user-modified instances. I was delighted to find it in the documentation because I was expecting to need to write my own routine. Unfortunately, it appears to require `match_lists_function` to be passed to it, and I can't find this function referenced anywhere else in the repository. There's no default matching function listed. Does such a thing exist? 

I want to compare predicted and user-generated instances for a specific model so that I can flag user-generated canonical instances that the model does a particularly bad job of predicting, just in case they're rough. In #1516 I have more context on that, but this would be an awesome function for building that except... that there's no clear options for this match_lists_function anywhere I can find on the github.

**Comment by roomrys** [comment]
I'd just like to point out as a word of warning that although the `matched_instance_distances` function is shipped with SLEAP, it is not used anywhere in the core package... meaning that it is undertested. #1520 adds a small test and additional development using this function (in regards to #1516) would also ensure/test it's reliability.

**Comment by roomrys** [comment]
Long awaited, but finally integrated. This issue is fixed in SLEAP 1.4.1.

**Comment by eringiglio** [comment]
Oh, wonderful, thank you so much!
