### ISSUE TITLE
Mac Visuals: Dark theme uses dark text for nodes table

### ISSUE THREAD

**Issue by roomrys** [talmolab/sleap#1527]
# Bug description
For some reason, the Nodes table uses a dark text that is near impossible to read if system settings has appearance set to dark:
<img width="497" alt="image" src="https://github.com/talmolab/sleap/assets/38435167/477be7fb-2c4c-4b47-99f4-7060a45d6283">
 
But, the videos table shows with a nice contrasting white text:
<img width="497" alt="image" src="https://github.com/talmolab/sleap/assets/38435167/1aa63170-cfdd-418d-a755-bc8fe90e3289">

## Expected behaviour
Contrasting text should always be used.

## Actual behaviour
Similar color text is used in the nodes table.

## Your personal set up

- OS: macOS 13.5
- Version(s): SLEAP v1.3.3, python 3.9
- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [x] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

**Comment by eberrigan** [comment]
Fixed by #1952 .
