### ISSUE TITLE
`sleap-export` in >= v1.3 yields frozen_graph pbs not compatible with Bonsai

### ISSUE THREAD

**Issue by jkbhagatio** [talmolab/sleap#1542]
We are able to export the pb model files successfully, however during runtime in Bonsai, with any type of model and its corresponding Bonsai node, we get the error: "Object reference not set to an instance of an object"

**Comment by jkbhagatio** [comment]
Hey @talmo , just poking again here. Would be happy to to help with this in any way I can. We'd love to be able to use 1.3.3 with Bonsai 🙏

**Comment by talmo** [comment]
Sorry for the long delay -- just as a status update we now have someone actively working on this! @ssrinath22

For other folks: This bug was introduced in 1.3.0, so SLEAP v1.2.9 should still work if this is a blocker for you.

**Comment by emilyjanedennis** [comment]
hey @talmo any update? we've hit the same problem. Will downgrade for now but would be nice to know

**Comment by jkbhagatio** [comment]
FYI this issue is solved in the 'develop' branch, so for those who need it asap, checking that out will work. Then just waiting for the merge and release.

**Comment by roomrys** [comment]
Long awaited, but finally integrated. This issue is now fixed in SLEAP 1.4.1.
