### ISSUE TITLE
Missing packages while installing with pip!

### ISSUE THREAD

**Issue by aarahvar2** [talmolab/sleap#1572]
I installed sleap with pip command in python 3.7.8 in Windows 10.

After installing I get a series of missing packages like:
No module named 'cattr'
ModuleNotFoundError: No module named 'sklearn'
ModuleNotFoundError: No module named 'jsonpickle'
ModuleNotFoundError: No module named 'cv2'

and so on.

**Comment by roomrys** [comment]
Hi @aarahvar2,

We did some dependency updates since 1.3.1 which require you to specify extras if [installing only through pip](https://sleap.ai/installation.html#pip-package):

```python
pip install sleap[pypi]==1.3.3
```

Thanks,
Liezl
