### ISSUE TITLE
crashing during predictions

### ISSUE THREAD

**Issue by msjindal** [talmolab/sleap#1580]
# Bug description

## Your personal set up

- OS:

- Version(s):

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```

</details>

## Screenshots

<img width="563" alt="Screenshot 2023-10-31 at 12 59 00 PM" src="https://github.com/talmolab/sleap/assets/122841338/51394888-5fb2-475b-983e-66a1048fc207">

**Comment by roomrys** [comment]
Hi @msjindal,

We have seen a few problems like this occur when the video is not [reliably seekable](http://blog.loopbio.com/video-io-1-introduction.html). Try [reencoding your video](https://sleap.ai/help.html#does-my-data-need-to-be-in-a-particular-format) and let us know how that works.

---
#### Update: If reencoding doesn't work, and results in `moov atom not found`
As I was helping a user, we found that they had just copied the contents of a zipped file over without unzipping which resulted in first the `KeyError`, and then, when attempting to reencode, a `moov atom not found` error. After retrying but with **unzipping first**, we were able to get everything running smoothly.

---

Related #767

Thanks,
Liezl
