### ISSUE TITLE
Transpose tracks feature not respecting propagate checkbox 

### ISSUE THREAD

**Issue by Marielamend** [talmolab/sleap#1637]
# Bug description
The transpose tracks feature (Ctrl + T) does not respect the propagate track labels checkbox.

## Expected behaviour
When the box is unchecked for the propagate track, pressing (Ctrl+T) should transpose for that given frame but should not propagate to the rest of the frames.

## Actual behaviour
Even when the checkbox is unchecked, pressing (Ctrl+T) continues propagating for the next frames.

## Screenshots

![Screenshot 2023-12-14 145539](https://github.com/talmolab/sleap/assets/120222245/9a10643e-0185-4175-b393-1475cddf6a09)

**Comment by roomrys** [comment]
Long, awaited, but finally integrated. This has been included in the SLEAP 1.4.1 release!
