### ISSUE TITLE
None option under training pipeline 

### ISSUE THREAD

**Issue by Marielamend** [talmolab/sleap#1646]
During proofreading, we found a "none" option under "Training/Inference Pipeline Type:" when attempting to run inference on a section of the video. 

![image_720](https://github.com/talmolab/sleap/assets/120222245/f12561a4-a48a-4b94-8930-4c5ae633ca01)

**Comment by roomrys** [comment]
Correct, that is if you just want to rerun the tracker (for non-id models) without running inference. Do you have another suggestion that would make it more clear?

**Comment by talmo** [comment]
Maybe we can just call it "Tracking-only"?
