### ISSUE TITLE
Add option to export to CSV via `sleap-convert` and API

### ISSUE THREAD

**Issue by eberrigan** [talmolab/sleap#1713]
It would be convenient to be able to export predictions stored in .SLP files to .CSV (see linked discussion).

## Enhancement plan

1. Add `csv` as an option for the `--format` flag in the `sleap-convert` CLI here:

https://github.com/talmolab/sleap/blob/2d24296c2149402c7ee07601e4d0272fdd308441/sleap/io/convert.py#L67-L75

2. If csv format is requested, use `csv=True` in the `sleap-convert` CLI entrypoint function:

https://github.com/talmolab/sleap/blob/2d24296c2149402c7ee07601e4d0272fdd308441/sleap/io/convert.py#L165-L172

3. The [CSV writing is already handled through the IO format backends](https://github.com/talmolab/sleap/blob/5fa10795f51fd25568c444dd95d370b86054acdc/sleap/io/format/csv.py), so we can just route it through by adding `csv` as an option in the actual analysis exporting writer:

https://github.com/talmolab/sleap/blob/2d24296c2149402c7ee07601e4d0272fdd308441/sleap/io/convert.py#L177-L181

### Discussed in https://github.com/talmolab/sleap/discussions/1629

<div type='discussions-op-text'>

<sup>Originally posted by **talmo** December  7, 2023</sup>
In #1438, we added a feature to export tracks to CSV format from the GUI.

It would be great to be able to do that via the `sleap-export` CLI and the `Labels.export()` API.

For `sleap-export`, we just need to add CSV as a target format and pass in `csv=True` in the [export call here](https://github.com/talmolab/sleap/blob/2d24296c2149402c7ee07601e4d0272fdd308441/sleap/io/convert.py#L165-L171).

For `Labels.export()`, we probably want to [extend what's going on here](https://github.com/talmolab/sleap/blob/2d24296c2149402c7ee07601e4d0272fdd308441/sleap/io/dataset.py#L2035-L2056).

We should also be sure to support the new functionality being added in #1624.

Relevant: #1627</div>

**Comment by roaldarbol** [comment]
Any idea when you're cutting a new release? This feature would be great to have without having to build from source. :-)

**Comment by talmo** [comment]
Soon™ :)

**Comment by roomrys** [comment]
Long awaited, but finally integrated. This issue has been fixed in the SLEAP 1.4.1 release!
