### ISSUE TITLE
Generate labels from score crashing GUI

### ISSUE THREAD

**Issue by dlhagger** [talmolab/sleap#1740]
# Bug description

I have a large number of frames (1.2M) from a long video (24 hours) and trained on all the frames to hopefully find labeling suggestions based on the prediction scores. When I attempt to load the labels from the predictions folder, it hangs on RAM and the GUI crashes. Am I doing this correctly, is there a more efficient way to load predictions for refinement?

I expect the GUI to load the predicted labels from the last training loop into the GUI and use the labeling suggestions to generate new frame to correct predictions on. 

Memory hangs during loading, and GUI becomes unstable and crashes

## Your personal set up

Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz
32.0 GB RAM
Windows 11 Pro - Build 22631.3374
NVIDIA RTX 4060 Ti

- Version(s):

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [X ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```

</details>

**Comment by eberrigan** [comment]
Hi @dlhagger,

Can you open the original labels project you used for training? You should be able to generate suggestions and get predictions on the suggested frames that way. I am not sure if there is something wrong with the predictions file. Also, just to clarify, are you trying to open multiple prediction files simultaneously?

Thanks!

Elizabeth
