### ISSUE TITLE
ZMQ port hardcoded and not editable via the GUI 

### ISSUE THREAD

**Issue by shrivaths16** [talmolab/sleap#1774]
[WIP]

As of now we do not have an option to choose the ZMQ ports via the GUI and it has been hardcoded to `tcp://127.0.0.1:9000` for the controller address and `tcp://127.0.0.1:9001` for the publish address. Sometimes there is an issue when there are multiple SLEAP applications that are open and trained with, leading to "ZMQError: Address already in use" as mentioned in discussion #1751. 

In order to solve this, we need to make some changes as listed below:

- [ ] Update frontend loss viewer GUI which has the ports hardcoded [here](https://github.com/talmolab/sleap/blob/18aad91d10508127cc4f8a398432c43e661546a9/sleap/gui/widgets/training_monitor.py#L290-L317)
- [ ] Update controller_address and publish_address in the [ZMQ section of the training job config](https://github.com/talmolab/sleap/blob/18aad91d10508127cc4f8a398432c43e661546a9/sleap/training_profiles/baseline.centroid.json#L134-L140) via the training editor GUI (just ask users to specify ports and assume that the base of the address is always tcp://127.0.0.1)

**Comment by talmo** [comment]
The `ZMQConfig` is used here to setup the `TrainingControllerZMQ` and `ProgressReporterZMQ`:

https://github.com/talmolab/sleap/blob/18aad91d10508127cc4f8a398432c43e661546a9/sleap/nn/training.py#L396-L412

Which is called from `setup_output_callbacks` here:

https://github.com/talmolab/sleap/blob/18aad91d10508127cc4f8a398432c43e661546a9/sleap/nn/training.py#L497

Which is called from `Trainer._setup_outputs` here:

https://github.com/talmolab/sleap/blob/18aad91d10508127cc4f8a398432c43e661546a9/sleap/nn/training.py#L851-L853

It uses the `TrainingJobConfig` to specify the ZMQ address/port, which derives from the loaded config file.

When calling from the CLI, we do already overwrite some parts of the config with the CLI provided options, for example, to enable/disable ZMQ entirely:

https://github.com/talmolab/sleap/blob/18aad91d10508127cc4f8a398432c43e661546a9/sleap/nn/training.py#L1924-L1928

Next to this block, we should also support specifying the ZMQ port explicitly and overwriting the appropriate config fields.
