### ISSUE TITLE
More (small) marker and label sizes

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#1861]
- [ ] Add a couple more default marker sizes
- [ ] Make the available marker sizes configurable via the preferences yaml
  - [ ] Make sure to add validation and fallback to a default set of sizes since this is user configurable

### Discussed in https://github.com/talmolab/sleap/discussions/1854

<div type='discussions-op-text'>

<sup>Originally posted by **olinesn** July  8, 2024</sup>
Hello,

I'm writing to ask if an additional marker and font size options could be added? Most of the larger options are not very useful, and the steps at the low end are too big. Maybe add "9" between 6 and 12 for fonts, and a "3" in marker sizes between 2 and 4?

Thanks!
Stefan</div>

**Comment by roomrys** [comment]
Long awaited, but finally integrated. This issue has been fixed in the SLEAP 1.4.1 release!
