### ISSUE TITLE
Deleting instance fatal error in sleap multi view

### ISSUE THREAD

**Issue by bmidler** [talmolab/sleap#2008]
Hi, I've been working with sleap multi-view (the latest version of [this branch](https://github.com/talmolab/sleap/tree/liezl/add-gui-elements-for-sessions)) and have observed and reproduced the following bug:

1. Inference is run on a frame.
2. Predicted instance appears.
3. Predicted instance is added to an instance group (this is key).
4. I attempt to delete the instance using Labels>delete instance.

When I do this, the instance is not deleted, and when I go to save the project an error message is thrown and, critically, the project file has been deleted.

**Comment by roomrys** [comment]
Hi @bmidler,

Apologies for the delay. I am attempting to recreate the issue, but am having trouble. Are you able to provide the error message you are getting in the terminal?

Additionally, are you able to provide us with a troubleshooting dataset? This would include just the slp file (no videos needed) with predictions on at least one frame (which we can then try adding to an instance group to see what is happening). If you feel comfortable providing that, please upload to [this form](https://docs.google.com/forms/d/e/1FAIpQLSfWBwcuZH8lxGyFabMAODLjSUE4YrSCYbrrnYvXCpgBqZpcJA/viewform).

Thanks,
Liezl

**Comment by bmidler** [comment]
Hi Liezl,
I've figured more out about this issue and uploaded a screencapture to the form. Specifically, the steps are these:

1. Predict instance on a frame.
2. Add instance to an instance group.
3. Delete predictions on current frame (other settings for deleting predictions--e.g. deleting all predictions--may also cause the issue).
4. Delete the instance.

Let me know if you have more question. I've attached a screenshot of the error message.![Image](https://github.com/user-attachments/assets/4072bef9-1a75-49c5-8d90-6f3174e80b22)

**Comment by roomrys** [comment]
Hi @bmidler, 

I tried to exactly recreate what you did in the video you sent over - thanks for that. But, I am still having trouble using my own dataset (I've sent you a video recording of my recreation failure on slack).

It would be very helpful to me if you could send me the slp file (no videos needed - thus it'd be relatively small data to be sent).

I need the slp file to have a prediction on the current frame (lmk which frame please). From there, I will investigate the slp using the sleap API to see if I see anything obviously strange. I will also use the vscode debugger to run the GUI, add the instance to an instance group, delete prediction, and figure out why the error we see is just the `PredictedInstance.__repr__ `.

You can upload the slp to [this form](https://docs.google.com/forms/d/e/1FAIpQLSfWBwcuZH8lxGyFabMAODLjSUE4YrSCYbrrnYvXCpgBqZpcJA/viewform).

Thanks,
Liezl
