### ISSUE TITLE
Frame cannot be read on inference on whole video

### ISSUE THREAD

**Issue by camilletestard** [talmolab/sleap#2027]
# Bug description

I have been trying to run inference on a model of two interacting mice but consistently hit an error when trying to infer the whole video whereby one frame, generally at the end of the video, cannot be read. This has been happening with all videos i have tried to run inferences on. 

What is strange is that the the specific frame in the specific video could be read in the GUI interface for labeling. All videos are in gray scale. I also tried running inference on RGB (color) scale but the same issue arises. 

Any clue as to why a frame in a video could be read in the GUI but not when predicting or inferring on the whole video? Thanks for the help!

## Expected behaviour

I expect all the frames to be predicted on.

## Actual behaviour

 I get an error indicating that one of the frames could not be read with no explanation as to why.
KeyError: "Unable to load frame 27667 from MediaVideo(filename='D:/2024_male_female_3 strains/FVB_male/FVB_male_3_day5_File20240902184915.Avi', grayscale=True, bgr=True, dataset='', input_format='')."

Please see full error log below.

## Your personal set up

- OS: Windows 11

- Version(s):

- SLEAP installation method: Conda from package (https://sleap.ai/installation.html#conda-package)
 
<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

# packages in environment at C:\Users\camil\anaconda3\envs\sleap:
#
# Name                    Version                   Build  Channel
absl-py                   1.0.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backports-zoneinfo        0.2.1                    pypi_0    pypi
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
ca-certificates           2024.7.4             h56e8100_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.4                    pypi_0    pypi
cattrs                    1.1.1              pyhd8ed1ab_0    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
charset-normalizer        2.0.9                    pypi_0    pypi
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
cuda-nvcc                 11.3.58              hb8d16a4_0    nvidia
cudatoolkit               11.3.1              hf2f0253_13    conda-forge
cudnn                     8.2.1.32             h754d62a_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0           py37hcc03f2d_0    conda-forge
dask-core                 2022.2.0           pyhd8ed1ab_0    conda-forge
efficientnet              1.0.0                    pypi_0    pypi
flatbuffers               2.0                      pypi_0    pypi
fonttools                 4.38.0           py37h51bd9d9_0    conda-forge
freeglut                  3.2.2                he0c23c2_3    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
fsspec                    2023.1.0           pyhd8ed1ab_0    conda-forge
gast                      0.4.0                    pypi_0    pypi
geos                      3.11.0               h39d44d4_0    conda-forge
google-auth               2.3.3                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.43.0                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hdmf                      3.6.1                    pypi_0    pypi
icu                       69.1                 h0e60522_0    conda-forge
idna                      3.3                      pypi_0    pypi
image-classifiers         1.0.0                    pypi_0    pypi
imagecodecs-lite          2019.12.3        py37h0b711f8_5    conda-forge
imageio                   2.34.2             pyh12aca89_0    conda-forge
imgaug                    0.4.0              pyhd8ed1ab_1    conda-forge
imgstore                  0.2.9                    pypi_0    pypi
importlib-metadata        4.10.0                   pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2024.2.0           h57928b3_979    conda-forge
jasper                    2.0.33               hc2e4405_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
jsmin                     3.0.1              pyhd8ed1ab_0    conda-forge
jsonpickle                1.2                        py_0    conda-forge
jsonschema                4.17.3                   pypi_0    pypi
keras                     2.7.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4            py37h8c56517_0    conda-forge
lcms2                     2.14                 h90d422f_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              22_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              22_win64_mkl    conda-forge
libclang                  12.0.0                   pypi_0    pypi
libdeflate                1.14                 hcfcfb64_0    conda-forge
libhwloc                  2.11.0          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
liblapack                 3.9.0              22_win64_mkl    conda-forge
liblapacke                3.9.0              22_win64_mkl    conda-forge
libopencv                 4.5.5           py37h542666b_10    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libprotobuf               3.20.3               h12be248_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.46.0               h2466b09_0    conda-forge
libtiff                   4.4.0                hc4f729c_5    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.12.7               h283a6d9_1    conda-forge
libxslt                   1.1.39               h3df6e99_0    conda-forge
libzlib                   1.3.1                h2466b09_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.6                    pypi_0    pypi
markdown-it-py            2.2.0              pyhd8ed1ab_0    conda-forge
matplotlib-base           3.5.3            py37hbaab90a_2    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mkl                       2024.1.0           h66d3029_692    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ndx-pose                  0.1.1                    pypi_0    pypi
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nixio                     1.5.3                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
opencv                    4.5.5           py37h03978a9_10    conda-forge
opencv-python-headless    4.2.0.34                 pypi_0    pypi
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   1.1.1w               hcfcfb64_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.5            py37h9386db6_0    conda-forge
partd                     1.4.1              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pillow                    9.2.0            py37h42a8222_2    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
protobuf                  3.19.1                   pypi_0    pypi
psutil                    5.9.3            py37h51bd9d9_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
py-opencv                 4.5.5           py37h90c5f73_10    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pykalman                  0.9.7              pyhd8ed1ab_0    conda-forge
pynwb                     2.3.3                    pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pyside2                   5.13.2           py37h760f651_8    conda-forge
python                    3.7.12          h7840368_100_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-rapidjson          1.9              py37h7f67f24_0    conda-forge
python_abi                3.7                     4_cp37m    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py37h3a130e4_1    conda-forge
pyyaml                    6.0              py37hcc03f2d_4    conda-forge
pyzmq                     24.0.1           py37h7347f05_0    conda-forge
qimage2ndarray            1.10.0                   pypi_0    pypi
qt                        5.12.9               h556501e_6    conda-forge
qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
ruamel-yaml               0.17.32                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
scikit-image              0.19.3           py37h3182a2c_1    conda-forge
scikit-learn              1.0              py37ha78be43_1    conda-forge
scikit-video              1.1.11             pyh24bf2e0_0    conda-forge
scipy                     1.7.3            py37hb6553fb_0    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
segmentation-models       1.0.1                    pypi_0    pypi
setuptools                59.8.0           py37h03978a9_1    conda-forge
setuptools-scm            6.3.2                    pypi_0    pypi
shapely                   1.8.5            py37h475e9a0_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleap                     1.3.3                    pypi_0    pypi
sqlite                    3.46.0               h2466b09_0    conda-forge
statsmodels               0.13.2           py37h3a130e4_0    conda-forge
tbb                       2021.12.0            hc790b64_2    conda-forge
tensorboard               2.7.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.7.0                    pypi_0    pypi
tensorflow-estimator      2.7.0                    pypi_0    pypi
tensorflow-hub            0.12.0             pyhca92ed8_0    conda-forge
tensorflow-io-gcs-filesystem 0.23.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2020.6.3                   py_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tomli                     2.0.0                    pypi_0    pypi
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.0.1                    pypi_0    pypi
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
tzlocal                   5.0.1                    pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py37hcc03f2d_1    conda-forge
urllib3                   1.26.7                   pypi_0    pypi
vc                        14.3                h8a93ad2_20    conda-forge
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.13.3                   pypi_0    pypi
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.6.0                    pypi_0    pypi
zstd                      1.5.6                h0ea2cb4_0    conda-forge

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
Here is the relevant log for the error in one example video 

Process return code: 0
Restoring GUI state...
Using already trained model for centroid: C:/Users/camil/Documents/Sleap/ReunionAssayDing_sex_strain\models\241115_182216.centroid.n=543\training_config.json
Using already trained model for centered_instance: C:/Users/camil/Documents/Sleap/ReunionAssayDing_sex_strain\models\241115_184517.centered_instance.n=543\training_config.json
Command line call:
sleap-track C:/Users/camil/Documents/Sleap/ReunionAssayDing_sex_strain/labels.v002.slp --video.index 4 --frames 0,-27675 -m C:/Users/camil/Documents/Sleap/ReunionAssayDing_sex_strain\models\241115_182216.centroid.n=543\training_config.json -m C:/Users/camil/Documents/Sleap/ReunionAssayDing_sex_strain\models\241115_184517.centered_instance.n=543\training_config.json --tracking.tracker simplemaxtracks --max_instances 2 --tracking.max_tracks 2 --tracking.similarity iou --tracking.match hungarian --tracking.track_window 5 --tracking.post_connect_single_breaks 0 --tracking.max_tracking 1 -o C:/Users/camil/Documents/Sleap/ReunionAssayDing_sex_strain\predictions\labels.v002.slp.241120_074124.predictions.slp --verbosity json --no-empty-frames

Started inference at: 2024-11-20 07:41:27.580800
Args:
{
    'data_path': 'C:/Users/camil/Documents/Sleap/ReunionAssayDing_sex_strain/labels.v002.slp',
    'models': [
        'C:/Users/camil/Documents/Sleap/ReunionAssayDing_sex_strain\\models\\241115_182216.centroid.n=543\\training_config.json',
        'C:/Users/camil/Documents/Sleap/ReunionAssayDing_sex_strain\\models\\241115_184517.centered_instance.n=543\\training_config.json'
    ],
    'frames': '0,-27675',
    'only_labeled_frames': False,
    'only_suggested_frames': False,
    'output': 'C:/Users/camil/Documents/Sleap/ReunionAssayDing_sex_strain\\predictions\\labels.v002.slp.241120_074124.predictions.slp',
    'no_empty_frames': True,
    'verbosity': 'json',
    'video.dataset': None,
    'video.input_format': 'channels_last',
    'video.index': '4',
    'cpu': False,
    'first_gpu': False,
    'last_gpu': False,
2024-11-20 07:41:28.596367: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
    'gpu': 'auto',
    'max_edge_length_ratio': 0.25,
    'dist_penalty_weight': 1.0,
    'batch_size': 4,
    'open_in_gui': False,
    'peak_threshold': 0.2,
    'max_instances': 2,
2024-11-20 07:41:28.950786: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9594 MB memory:  -> device: 0, name: NVIDIA RTX A2000 12GB, pci bus id: 0000:01:00.0, compute capability: 8.6
    'tracking.tracker': 'simplemaxtracks',
    'tracking.max_tracking': True,
    'tracking.max_tracks': 2,
    'tracking.target_instance_count': None,
    'tracking.pre_cull_to_target': None,
    'tracking.pre_cull_iou_threshold': None,
    'tracking.post_connect_single_breaks': 0,
    'tracking.clean_instance_count': None,
    'tracking.clean_iou_threshold': None,
    'tracking.similarity': 'iou',
    'tracking.match': 'hungarian',
    'tracking.robust': None,
    'tracking.track_window': 5,
    'tracking.min_new_track_points': None,
    'tracking.min_match_points': None,
    'tracking.img_scale': None,
    'tracking.of_window_size': None,
    'tracking.of_max_levels': None,
    'tracking.save_shifted_instances': None,
    'tracking.kf_node_indices': None,
    'tracking.kf_init_frame_count': None
}

INFO:sleap.nn.inference:Auto-selected GPU 0 with 12110 MiB of free memory.
2024-11-20 07:41:33.012616: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8201
Versions:
SLEAP: 1.3.3
TensorFlow: 2.7.0
Numpy: 1.21.6
Python: 3.7.12
OS: Windows-10-10.0.22621-SP0

System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True

2024-11-20 07:49:34.645804: W tensorflow/core/framework/op_kernel.cc:1733] UNKNOWN: KeyError: "Unable to load frame 27667 from MediaVideo(filename='D:/2024_male_female_3 strains/FVB_male/FVB_male_3_day5_File20240902184915.Avi', grayscale=True, bgr=True, dataset='', input_format='')."
Traceback (most recent call last):

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\script_ops.py", line 273, in __call__
    return func(device, token, args)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\script_ops.py", line 151, in __call__
    outputs = self._call(device, args)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\script_ops.py", line 158, in _call
    ret = self._func(*args)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 649, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\sleap\nn\data\providers.py", line 405, in py_fetch_frame
    raw_image = self.video.get_frame(frame_ind)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 1104, in get_frame
    return self.backend.get_frame(idx)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 496, in get_frame
    raise KeyError(f"Unable to load frame {idx} from {self}.")

KeyError: "Unable to load frame 27667 from MediaVideo(filename='D:/2024_male_female_3 strains/FVB_male/FVB_male_3_day5_File20240902184915.Avi', grayscale=True, bgr=True, dataset='', input_format='')."

Traceback (most recent call last):
  File "C:\Users\camil\anaconda3\envs\sleap\Scripts\sleap-track-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.3.3', 'console_scripts', 'sleap-track')())
  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 5424, in main
    labels_pr = predictor.predict(provider)
  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 526, in predict
    self._make_labeled_frames_from_generator(generator, data)
  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 2633, in _make_labeled_frames_from_generator
    for ex in generator:
  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 455, in _predict_generator
    for ex in self.pipeline.make_dataset():
  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 800, in __next__
    return self._next_internal()
  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 786, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2844, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\framework\ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.UnknownError: KeyError: "Unable to load frame 27667 from MediaVideo(filename='D:/2024_male_female_3 strains/FVB_male/FVB_male_3_day5_File20240902184915.Avi', grayscale=True, bgr=True, dataset='', input_format='')."
Traceback (most recent call last):

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\script_ops.py", line 273, in __call__
    return func(device, token, args)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\script_ops.py", line 151, in __call__
    outputs = self._call(device, args)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\script_ops.py", line 158, in _call
    ret = self._func(*args)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 649, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\sleap\nn\data\providers.py", line 405, in py_fetch_frame
    raw_image = self.video.get_frame(frame_ind)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 1104, in get_frame
    return self.backend.get_frame(idx)

  File "C:\Users\camil\anaconda3\envs\sleap\lib\site-packages\sleap\io\video.py", line 496, in get_frame
    raise KeyError(f"Unable to load frame {idx} from {self}.")

KeyError: "Unable to load frame 27667 from MediaVideo(filename='D:/2024_male_female_3 strains/FVB_male/FVB_male_3_day5_File20240902184915.Avi', grayscale=True, bgr=True, dataset='', input_format='')."

         [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]

Process return code: 1

**Comment by gitttt-1234** [comment]
Hi @camilletestard,

We've seen this issue before when a video is not reliably seekable. I'm linking a previous issue which addresses this problem and proposes potential solutions (re-encoding your video). 

https://github.com/talmolab/sleap/discussions/767

Let me know if you have any more questions!

Thanks,

Divya

**Comment by camilletestard** [comment]
Solved my issue! thanks!
