### ISSUE TITLE
Running inference in batch on all videos via GUI

### ISSUE THREAD

**Issue by calebvogt** [talmolab/sleap#497]
OS: Windows, running locally with GPU
SLEAP version: stable v1.0.10

Issue: I have trained a model and successfully used it to run inference over a single video using the GUI exclusively. However, I cannot seem to find a way to run inference over all videos in the project via the GUI.  My sense from looking over docs and notebooks is that most users are doing this via the command line.  If it doesn't exist already, in a future SLEAP release it would be awesome to have a "Predict on: All Project Videos" option in the following drop down menu: 

![image](https://user-images.githubusercontent.com/15038280/109443147-ceee1000-7a07-11eb-8a83-31b98b543037.png)

For anyone else having this issue, here is an ugly, yet functional "batch.py" script that can be used to batch run your model over your videos. Note that batch.py should be placed in your project folder with all the videos you want it to run on. 

Copy and paste the following into a text editor and save as "batch.py" in your working directory. Make sure to edit the script to point to the folder containing your model before running it. 

##########
import os
import subprocess
subprocess.call('(for %i in (*.mp4) do sleap-track ''%i'' -m "models/210226_161753.single_instance.2819")', shell=True)   ###  CHANGE FOR SINGLE OR MULTI-ANIMAL MODEL

###########

![image](https://user-images.githubusercontent.com/15038280/109443823-951e0900-7a09-11eb-8227-03cc370d0fd9.png)

In the shell: 
> cd /d  /your/working/directory
> conda activate sleap
> batch.py

Hopefully someone finds this temp fix useful. If there is another (more elegant) way to batch run inference please let me know!

**Comment by ariematsliah-princeton** [comment]
HI @calebvogt,
Thanks for the feedback and for writing up this workaround that could also help other SLEAP.
We have a list of GUI improvements planned in our queue, and we'll also keep track of this enhancement request.

Cheers

**Comment by talmo** [comment]
Closing this one, but follow #733 for progress on this issue.
