### ISSUE TITLE
Cannot run the labeling GUI 

### ISSUE THREAD

**Issue by ym442** [talmolab/sleap#594]
Hi developers,

I installed SLEAP on my Windows computer and could activate the SLEAP conda environment. But when I typed "sleap-label" to run the labeling GUI, I got an error message saying "failed to create process". I installed SLEAP on two computers in our lab and tried to run the GUI but neither worked. 

Here is the info of our computer and GPU.

Device name	DESKTOP-8C1JJ6A
Processor	Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz   3.31 GHz
Installed RAM	64.0 GB (63.7 GB usable)
Device ID	1DAAB813-ED9A-4ECE-B40E-B7D387E12309
Product ID	00329-00000-00003-AA426
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

GeForce GTX 1060
CUDA version 10.1.243
CUDNN version 7.6.5

I would really appreciate any help to solve this issue.
Thank you in advance!

Best,
Yuta
<img width="1280" alt="error" src="https://user-images.githubusercontent.com/76564872/137344363-550d0692-c891-4c65-a251-cf6e410dc0d6.png">

**Comment by lblabucsd** [comment]
Dear Talmo, I hope you’re well. I’m running into the same problem as Yuta. It looks like I could install sleap (packages were downloaded and 5.8 GB of folders were created in: C:\Users\LB Lab setup #2\.conda\envs\sleap), however I cannot open the gui using “sleap-label” (error: “failed to create process.”) .
Like Yuta, I have a space in my path, however I don't have the same issue when opening jupyter notebook for example as can be seen in the attached screenshot. Hence, I wonder if there is another way to solve the opening of sleap apart from installing anaconda from scratch?
I’d be super grateful for your feedback.
Have a great day and best regards, 
Lisanne  

![220405_sleap-label_gui_error](https://user-images.githubusercontent.com/69403596/161866630-b804f165-7dc4-48dc-be71-1fe662f7f7df.png)

**Comment by talmo** [comment]
Hi @lblabucsd,

It'll probably definitely be easier to reinstall it, but if you want to try it, there's a [workaround described here](https://stackoverflow.com/a/47081531).

If that doesn't work, we have [instructions on installing Miniconda on Windows](https://sleap.ai/installation.html#installing-miniconda) that should do the trick.

Let me know if either works for you!

Cheers,

Talmo

**Comment by lblabucsd** [comment]
Dear Talmo,
Thanks a lot for the quick reply! Reinstalling anaconda under a different path did the job for me, too. Looks like the tracking is working very well. Impressive. 
Best regards, 
Lisanne

**Comment by roomrys** [comment]
I recently helped a user correct this on their system, and while it is likely not the best solution, we got it working by:

0. [Uninstalling miniconda](https://docs.anaconda.com/anaconda/install/uninstall/?highlight=uninstall)
1. Installing miniconda to C:/miniconda3 with the following options selected:
- install for all users
- "Register Anaconda as my default Python"
2. [Installing sleap](https://sleap.ai/installation.html#conda-package) in the anaconda terminal using the usual command modified by:
- removing the "-n sleap" 
- adding a new [path to store the environment](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#specifying-a-location-for-an-environment) (--prefix <path_without_spaces>, i.e. `--prefix C:/Users/Public/sleap`)

```
conda create -y -c sleap -c nvidia -c conda-forge sleap --prefix C:/Users/Public/sleap
```
By this point things were working. For ease of use, we set the path to the sleap environment as an environment variable (accessible through `%<name_of_env_variable>%`):

3. Setting the path as an environment variable `setx sleap C:/Users/Public/sleap`
4. Opening a new Anaconda terminal! and activating the environment with `conda activate %sleap%`

---

There has to be a way to change where conda is storing environments by default. This post does not include that solution (which is probably the best solution), but proves that where the conda environment is being stored also matters (no spaces)!
