### ISSUE TITLE
CUDA version question

### ISSUE THREAD

**Issue by jverpeut** [talmolab/sleap#595]
I was just wondering if there will be an update to include CUDA 11 or a workaround?  I have a way to run everything, but there are particular nodes which are faster on our cluster and cannot be adjusted to downgrade to 10.

**Comment by talmo** [comment]
Hey Jess,

We're working on an update now that will address this issue. To keep track of the progress, follow #454 -- which also has a Docker-based workaround if that's a possibility in your cluster.

More soon.

Cheers,

Talmo
