### ISSUE TITLE
Shifted predictions when predicting on videos with different aspect ratio

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#596]
It looks like the predictions are slightly off when predicting on videos that have a different aspect ratio than those used for training.

This was supposed to be fixed in v1.1.3 (in #524), but it seems to still be happening in some(?) cases.

**Workaround:**
![image](https://user-images.githubusercontent.com/3187454/138136923-eebb4055-4740-4813-9f45-f7a6835abf2f.png)
Disable this functionality by editing `training_config.json` for each model used for inference and setting: `"resize_and_pad_to_target": false`.

**Related issues:** #516, #584

**Comment by talmo** [comment]
It is not clear if this remains as an issue, but we should at a minimum add some tests here:

- With and without `resize_and_pad_to_target` enabled
- With `sleap.Video`s from both `MediaVideo` and `SingleImageVideo` sources (e.g., DLC imports)
- Integration test so we actually run a compiled pipeline (pulling from `tf.data.Dataset` examples) and not just the standalone transformer ([`SizeMatcher`](https://github.com/talmolab/sleap/blob/391bc0421fe3820ddd6b5d07e31311d60b129fe3/sleap/nn/data/resizing.py#L255))

**Comment by leonardolv** [comment]
Hi,

I'm using SLEAP from the source, and I have the problem described above.
My model is trained with different aspect ratio videos than the ones I'm predicting on.
Then I predicted on several videos and the predictions are shifted, as you can see in the attached picture. Also one of the markers (tail base) is not in the correct position...

Do I need to predict again with the solution above or can I just apply it after the analysis?

![RAT SLEAP](https://user-images.githubusercontent.com/49067627/170667886-58aa2a43-91db-4514-af94-3daa31a188b4.png)

SLEAP is very useful BTW, thanks!

Leonardo

**Comment by roomrys** [comment]
Hi @leonardolv,

Thanks for confirming that this remains an issue! We will work on providing a more permanent fix.

The `training_config.json` is used during inference and thus needs to be edited before making the predictions. Unfortunately, you will need to make the above changes to each `training_config.json` used during inference and predict again.

Thanks,
Liezl

**Comment by leonardolv** [comment]
Hi @roomrys,

I edited the training_config.json as @talmo suggested but it does not work.
There is an error that prevents inference in any video I've tried...
This is the error:

![ERROR SLEAP](https://user-images.githubusercontent.com/49067627/171106385-00e8761a-1eba-4b62-b56d-e3dc50159224.png)

Please let me know if you need more info about the bug.

Is there any other solution to this shift in predictions?

Thanks,

Leonardo

**Comment by roomrys** [comment]
Hi @leonardolv,

Can we solicit you for a sample video and model please? If you can send the info to liezlmaree8@gmail.com that would be perfect.

Thanks,
Liezl

**Comment by leonardolv** [comment]
Hi @roomrys,

Sorry for the late response.
Unfortunately I deleted all the videos with different sizes and started over from scratch.

Thanks for your answer.

Best, 

Leonardo

**Comment by roomrys** [comment]
Please share data (models + .slp + videos) with [lmaree@salk.edu](mailto:lmaree@salk.edu) if you happen to come across this bug.
---

#### Update: Attempting to recreate

- I trained a model on a 1024 X 1024 video then cropped a copy of the video to 768 X 1024 with an x-offset of 128. The model predicted fine on both videos. 
- I then repeated the crop in the y-direction (w/ y-offset as well). The predictions were fine. 
- I predicted through `sleap-track` and through the GUI (loading both cropped and uncropped, then again with just the cropped) - both methods resulted in good predictions.

#### Ideas:

1. Maybe there is a problem with scaling up (the tests above only scale down)

Thanks,
Liezl

**Comment by anas-masood** [comment]
Hey, any update to this? We are facing the same issue when trained the network with video sizes of 1248x1248 but now predicting on a different video size (1408x1408). We are doing this because we were losing some corners

**Comment by roomrys** [comment]
Hi @anas-masood,

I just ran a quick test and training the network with images/videos of different size still results in offset predictions in the videos where SLEAP tries to automatically rescale the image/video. I have shifted my focus back to this PR and will post updates here.

Thanks,
Liezl

**Comment by anas-masood** [comment]
@roomrys , thanks so much. For now we have trained another network on our desired resolution but reading (superficially) through the doc i found that the tracker and network both crop and resize for data augmentation meaning the network prediction should be robust to this. Must be happening at rescaling (scaling back) the node values to the input image. Don't know if i am totally correct though. Would love to start contributing and testing but have loads on my plate. Bonne chance and let me know if you find a solution.

**Comment by roomrys** [comment]
Hi @anas-masood,

The fix has been merged into develop and will be available in the next release. Alternatively, you can [install SLEAP from source](https://sleap.ai/installation.html#conda-from-source) to get the fix now.

Thanks,
Liezl

**Comment by roomrys** [comment]
This issue has been resolved in the new release - install [here](https://sleap.ai/installation.html#conda-package).
