### ISSUE TITLE
Labeling suggestion: Rescale and mirror/rotate labels from previous frame 

### ISSUE THREAD

**Issue by Souvik-Mandal-Harvard** [talmolab/sleap#602]
Currently, the skeleton containing the positions of the manual labels get copied from the previous frame, and users can move the whole skeleton according to the location of the animal in the new frame. This is very useful when the animal retains the same body size and orientation. But if the animal changes its relative distance from the camera (and thus, its size in the frame) and/or its body orientation, the user needs to drag each point to the new location which could be cumbersome. It will be great if there is a shortcut to
1. rescale the skeleton, and
2. mirror or rotate/change the orientation of the skeleton.

Thanks!

**Comment by talmo** [comment]
Mirroring and rescaling are definitely doable.

You can currently already rotate and translate the whole skeleton by holding Alt/Option + Scrolling or dragging:
![](https://sleap.ai/_images/labeling.gif)

**Comment by Souvik-Mandal-Harvard** [comment]
Thanks!

**Comment by talmo** [comment]
Closing this issue as scaling is now possible (#1107 -> #1133).

We can revisit mirroring in the future if requested again.
