### ISSUE TITLE
Importing DLC frames to train on SLEAP 

### ISSUE THREAD

**Issue by Charlottewiltshire97** [talmolab/sleap#606]
Hi!
Firstly, I apologise for my lack of knowledge here and if any of this is an easy fix. I am attempting to transfer my DLC labelled dataset into SLEAP for training. I want to compare the two softwares. 

I have ran file>import>multiple DLC datasets from folder. SLEAP has done a great job importing these labels but I have a few questions I was hoping you could help with:
1) the 'greyed out' labels. These are labels which are not present in the frame and therefore not marked in DLC. They have appeared on SLEAP as a 'greyed out' label within the bounding box for each animal. The Instances tab is showing 18/18 labels for each animal. Does this mean these are being picked up as present, despite looking different from the DLC imported labels?

2) SLEAP has also imported the labelled cropped images that DLC uses to train. Again, SLEAP has done a great job importing these DLC cropped image labels but I am unsure if SLEAP will crop images itself during training and therefore, for the sake of comparison, I should remove these cropped images? 

3) Is there a way to link the 25 imported (manually labelled) DLC frames per video to their original video? In DLC, there is a 'link' and, after training, I can go on to "fill in" the rest of the video after training. Can I do this on SLEAP?

Thank you in advance for your help. If there are any guides or tutorials which could help me with this process, please let me know.

**Comment by talmo** [comment]
Hi @Charlottewiltshire97,

1. Greyed out points will be marked as "missing", so no worries about them impacting training.
2. Cropping is still not implemented automatically, but we'll be working on it (I'll mark this as an enhancement). In the meantime, you can either exclude those or crop them manually.
3. That's a bit trickier -- that involves parsing a lot of extra metadata that may not be readily available. I'll flag this as something we can look into, but for right now what I'd recommend is to just import those videos into SLEAP and re-running inference to predict on them as if they were new videos.

Let me know if you have any questions!

Cheers,

Talmo

**Comment by Charlottewiltshire97** [comment]
Hi Talmo,

Thank you so much for your help! I have managed to successfully train on SLEAP using my DLC labelled frames with no issues. Having this feature is super helpful and I am enjoying exploring SLEAP without having to re-mark thousands of frames. 

I am sorry to bother you with yet another question, but I was wondering if SLEAP also copies the same test/train split (does it use the same frames?) when it takes data from DLC. I want to compare performance so it would be nice to know if they are testing on the same frames or not. 

Thanks in advance,
Charlotte

**Comment by talmo** [comment]
Hi @Charlottewiltshire97,

It does not copy the train/test split currently. I'm not 100% sure where that information is stored in the DLC project metadata, but if you don't mind sharing with me an example dataset I could have a look to see how easy this would be to add.

Cheers,

Talmo

**Comment by talmo** [comment]
Closing this but we will be tracking these feature requests in #734.
