### ISSUE TITLE
Generate suggestions only from current video

### ISSUE THREAD

**Issue by olinesn** [talmolab/sleap#627]
Sometimes when adding videos to a .slp project that have slightly different features (animal is now implanted), I want to generate randomly sampled suggested frames only from this new video. Could there be an option in the "Generage Suggestions" box to select which videos to draw from?

Thanks!

**Comment by davidasamy** [comment]
## Problem Analysis
Currently SLEAP generates suggestions for all videos at once in a project. There is no option to generate suggestions for individual videos or sets of videos.

## Proposed Solution(s)
Add an option for users to select videos to generate suggestions (e.g. drop-down menu) in the Generate Suggestions dialog box.

## Test
Tests should go in `test/gui/test_suggestions.py` and test:
- [ ] Suggestions can be generated for one, multiple, or all videos in a project.

## Relevant files/functions
- [L43](https://github.com/talmolab/sleap/blob/e02cee0cd920ea2f283cbfd92e3acff0a76c9eb1/sleap/gui/suggestions.py#L43) `VideoFrameSuggestions.suggest()` from `sleap/gui/suggestions.py`

**Comment by roomrys** [comment]
Hi @olinesn,

The new release of SLEAP v1.2.4 is now available for [installation](https://sleap.ai/installation.html) and includes this fix.

Thanks,
Liezl
