### ISSUE TITLE
Exporting to analysis HDF5 should use user-labeled instance instead of predicted instance when available

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#637]
Currently, proofreading is primarily used to correct track identities to fix swaps and etc.

To adjust one or more landmarks, you have to double click on the prediction to create a user instance from it with nodes that are movable.

The problem is that both the original predicted instance and the new (corrected) user instance are both still stored in the labels. This could result in the original predicted instance being used instead of the new user instance when exporting to an analysis HDF5 file.

Thanks @olinesn for raising this issue!

----

Solutions:

1. We should explicitly check for linked predicted <-> user instances by inspecting the [`Instance.from_predicted`](https://github.com/talmolab/sleap/blob/391bc0421fe3820ddd6b5d07e31311d60b129fe3/sleap/instance.py#L369) attribute.
2. We could just write out all the predicted instances to the appropriate tracks and _then_ the user instances, overwriting any predicted instances in the corresponding track channels of the exported tracks array.

The first option is more general and would work even when the `Instance.track` attribute isn't set (e.g., for single instance videos).

**Comment by olinesn** [comment]
Thanks for documenting!

**Comment by roomrys** [comment]
Hi @olinesn ,

The new release of SLEAP v1.2.4 is now available for [installation](https://sleap.ai/installation.html) and includes this fix.

Thanks,
Liezl
