### ISSUE TITLE
Finding Predicted Frames 

### ISSUE THREAD

**Issue by zhc018** [talmolab/sleap#641]
Hi, 

I wonder how I can find the predicted frames if I label many frames but only predict on a small number of frames. On the seek bar, I will only be able to see the labeled frames, and the predicted ones are covered and become hard to locate. 

<img width="706" alt="57ae2f6e636e5ede37b5b806f58d2a6" src="https://user-images.githubusercontent.com/77309671/152840898-a53f764e-717f-4abf-b321-460376a355c1.png">
For example, in the picture I attached, there are so many labeled frames (blue) that the predicted ones (yellow I assume) are buried. 

Thank you very much!

**Comment by talmo** [comment]
Hi @zhc018,

Apologies for the late response. I know you created another issue where you mentioned the same problem (#633) -- I just hadn't had time to dig into it yet.

You're right, there isn't a way to navigate exclusively to predicted frames (which show up in cyan), which I appreciate can be an issue when you have a lot of user labeled frames (which show up in dark blue).

I'm tagging this as an enhancement since it should be a relatively easy thing to add and we can include it in the next update.

That said, for both this and #633, it sounds like the underlying issue is that you have _many_ user labeled frames. A core idea with SLEAP is that you should definitely be labeling fewer frames than you're predicting on -- otherwise it kind of defeats the purpose of automation.

Do you mind describing a bit more about your workflow/application?
Do you keep getting bad predictions so you're labeling more frames?

Thanks,

Talmo

**Comment by zhc018** [comment]
@talmo 
Hi, thank you for your response! Here is an explanation of what I'm trying to do.

I was told by another lab member to first predict on a small number of frames and check their accuracy. Then I'm supposed to manually correct ones that are inaccurate and include them together with labeled frames and run a second training. Then I shall repeat this process until the predicted frames are very accurate before generating large numbers of predicted frames. 

I don't know if this is the correct/best way to do so. I will be more than glad to receive some advice! 

Thank you very much!

**Comment by talmo** [comment]
Hi @zhc018,

Sorry for the delay!

That workflow is generally correct, but I guess what I'm wondering is why you end up correcting so many of the predicted frames. If you're correcting more than ~10% of the predictions (which is a lot), that's probably an indication that there's something else you could be doing to improve the performance. For instance, you'd perhaps want to consider tweaking the model parameters or something else about your setup.

In your labeling project, how many videos are you including? You should be able to train a single model for many videos if they don't differ too drastically in appearance.

How many labeled frames are you training with at the most?

Talmo

**Comment by zhc018** [comment]
Hi, @talmo 

Don't worry about the delay! Thanks a lot for your response! 

I'm currently working in a video-by-video manner. Each video has ~26000 frames and I was told to label 200 frames for each of them and run separate training. How do I use a single model for many videos? I do have lots of videos that are alike. 

The largest set of frames I trained on was 60 (because I don't want to correct too many frames), using Shift and drag on the seek bar. I had to correct around 20 of them. It seems a lot but it was because many frames were almost the same and the predictions were also the same, so I just corrected a few mistakes many times. I wonder if there is a way to select how many frames to predict on but still select them randomly because if I use Shift and drag, frames will be so close that many of them will be the same (and I will have to correct one mistake many times).  Or should I select predict on "user labeled frames"?

Could you please also give some tips to improve the prediction accuracy? Thank you very much!

**Comment by talmo** [comment]
Hi @zhc018,

Check out our tutorial where we have some instructions for these steps:
- Adding multiple videos to the project: https://sleap.ai/tutorials/new-project.html
- Using the Suggestions list to generate random frames as labeling targets: https://sleap.ai/tutorials/initial-labeling.html
- Some info on model selection and hyperparameters: https://sleap.ai/guides/choosing-models.html#choosing-models

Give those a go and let me know how it goes for you. After that, if you'd like to send over some example videos/predictions I'm happy to provide suggestions.

Cheers,

Talmo

**Comment by talmo** [comment]
Closing this one but we're tracking this as a broader feature enhancement in #736.
