### ISSUE TITLE
Trail options

### ISSUE THREAD

**Issue by olinesn** [talmolab/sleap#663]
Hello,

I'm writing to request a few more options for the trail. 

1. Would be nice to have a trail length option of ~30 to correspond to a 1s window for 30 fps
2. An option to select the node for the source of the trail would be great. Sometimes "Nose" is good, but other times something like a centroid would be better since switching while animals are nose-to-nose can be hard to catch. Having the option for two trails would be even better (I would personally select one for nose and one for centroid).
3. Setting the color of the trail to be 50 or 75% the value of the skeleton color (so just a bit darker) would make it easier to see yet still follow the color schemes that already exist.

Thanks!

**Comment by talmo** [comment]
Closing this one to track these changes in #605.
