### ISSUE TITLE
Importing DLC frames and frame distortion

### ISSUE THREAD

**Issue by Charlottewiltshire97** [talmolab/sleap#666]
Hi SLEAP.

I have managed to import a DLC dataset, train and run inference using SLEAP with no issues. This is a wonderful feature and would like to thank you for giving me an easy option for exploring your software! 
 
However, predications on novel videos appear as if the frame size has been distorted. It appears as if the dots move as the animal does, but it is in the wrong place on the frame. Is this an issue involving frame sizes? We have a mixture of 540x960 and 1080x1920 (in both the training frames and the novel frames). I have added a screenshot of one of the videos which hopefully shows the error. 

Thank you in advance for your help!

Charlotte

**Comment by talmo** [comment]
Hi @Charlottewiltshire97,

This might be an issue with the mixed sizes, but let's check that next.

First, have you tried [this possible fix](https://sleap.ai/help.html#i-get-strange-results-where-the-poses-appear-to-be-correct-but-shifted-relative-to-the-image)?

Next, can you try updating to SLEAP v1.2.0a6 and seeing if you get the same issue? (We changed some stuff in the pre-release that might affect this.)

Let me know if either of those do anything -- if not, shoot me an email (`talmo@salk.edu`) with an example video or clip where you see this happening, as well as the trained model(s) you're using.

Cheers,

Talmo

**Comment by talmo** [comment]
Hi @Charlottewiltshire97,

Any luck with the suggestions above?

Cheers,

Talmo

**Comment by Charlottewiltshire97** [comment]
Hi @talmo 

Sorry for the delay in response, work got quite hectic! However, things should settle down by next week and I will give your suggestions a try. Thank you so much for your response and I will let you know how it goes!

Best wishes, 
Charlotte

**Comment by talmo** [comment]
Closing this one due to inactivity and being a potential duplicate of #596. We'll follow up there.
