### ISSUE TITLE
Node placement bug

### ISSUE THREAD

**Issue by olinesn** [talmolab/sleap#669]
Hello,

I've got a bug when using the 1.2.0a6 build: When dragging a node, if you change frames before you've release the node (still holding left click) and then release after you've pressed the next frame button, when you return to the labelled frame, attempting to correct that node's placement slingshots it into the top left corner of the screen.

Simple fix would be to return the node to its original position before it got dragged.

Thanks,
Stefan

**Comment by talmo** [comment]
_Update_: @roomrys has done some work to investigate this issue, but it turns out to require significant architectural changes to how we render instances on new frames and how it interacts with mouse event callbacks.

We'll revisit this at some point in the future.

**Comment by roomrys** [comment]
## Observations
- It does not matter which node/instance/frame was dragged outside the frame, the first point dragged after the event jumps to `(0, 0)` even if it is a completely different instance on a different frame
- The node always jumps to `(0, 0)`
- `QtVideoPlayer` is in a potential drag event (with the cursor rendered as an open-hand when hovering over the video player image)
- Pressing the `Alt` key and dragging the entire instance does not result in the bug
- The nodes on the instance are loaded (and therefore set) as expected
