### ISSUE TITLE
feature request for making video annotations

### ISSUE THREAD

**Issue by kylethieringer** [talmolab/sleap#670]
Hi!

I was wondering if it would be possible to add a feature to help annotate videos as I skim through them. Something like where I hit a hotkey to mark a frame (or selection of frames) and this gets added to an annotations table. 
For Example,
| type  |  start  |  stop  |
|:-----|:------|:------|
| behaviorSegment   |  34552     |  34640    |
| behaviorEvent | 40220 | 40220|

This would help with manually marking behaviors, marking clips to analyze later, etc. I dont know if this could then be incorporated into the .slp dataset file and accessed when exporting to an .h5 or if its easier to have an option to just export the annotations to a .csv file directly from the GUI?

Thanks!

**Comment by talmo** [comment]
Hey @kylethieringer,

This would be a great feature to have and would definitely help to bootstrap some downstream behavior segmentation stuff.

I'll add it to the list, but I'll just say that it might be a bit tricky to implement for a little bit (especially the segments). We can try for a basic version of it after the next stable version release.

Cheers,

Talmo

**Comment by talmo** [comment]
I agree that our GUI framework is nice for this purpose and if you're using it already to do pose annotation, it would be helpful to be able to do everything in one place.

... but I'm going to close this for now, although we might revisit this functionality request in the future. It is a fairly large feature that we would need to add, and segmentation is a bit outside of the scope of what SLEAP is designed for.

In the meantime, we suggest checking out [BENTO](https://github.com/neuroethology/bento) from Ann Kennedy's lab which is explicitly designed to do this and now supports SLEAP inputs as well (https://github.com/neuroethology/bento/pull/144).
