### ISSUE TITLE
Many suggested frames slow down GUI

### ISSUE THREAD

**Issue by olinesn** [talmolab/sleap#695]
Hello,

Writing to make a note that having a long list of suggested frames can substantially slow down the gui. 

Sometimes I'll scrub through a video and add current frame when I get to tricky frames, or regions where I'll be doing a lot of tracking. I then run inference on this large list of suggested frames, sort by Mean Score, and label lots of the worst-scoring frames. However, the gui gets really laggy. I know that it's specifically the list of labelling suggestions, because after I run inference on the list, if I "Clear all" the problem goes away, even if I keep the predicted instances.

Best,
Stefan

**Comment by olinesn** [comment]
To be specific, one example would be moving to a fresh frame, and then double-clicking on a predicted node to begin correcting. There's a lag between the double-click and when the node becomes editable. A second example is that scrubbing through frames by holding down the GO TO Next Frame button becomes laggy with hundreds of suggested frames.

**Comment by roomrys** [comment]
[SLEAP v1.2.3](https://sleap.ai/installation.html) has been released and includes speed-up when searching labeling suggestions.
