### ISSUE TITLE
Better support for visualization options when rendering clips

### ISSUE THREAD

**Issue by crazyhathello** [talmolab/sleap#706]
**Problem**: The clip renderer supports only a subset of the visualization features in the native GUI. This is because we have to re-implement a lot of the rendering using OpenCV functions.

**MVP:** Implement the current visualization options in OpenCV, including the edge wedge display, thicknesses, etc. Most of these are properties that already exist in the renderer class that can be edited in the code (see below in the thread). They should just be exposed in the rendering GUI where we have the other options.

**Alternative:** Stop using the OpenCV renderer and instead capture the pixels from the [`QtVideoPlayer`](https://github.com/talmolab/sleap/blob/391bc0421fe3820ddd6b5d07e31311d60b129fe3/sleap/gui/widgets/video.py#L180) scene so the rendered output is identical to what the user sees in the GUI (and so we don't need to re-implement all the rendering routines).

----

_Original issue:_

Hello!
I was using the "Wedge" edge style for my project, and it seems like the edge style does not carry over when rendering video clips. In addition to edge styles, node marker size and node labels are not displayed properly in the rendered video clip. 

I've tried both selecting and unselecting the "Use GUI visual settings" option in the render video menu, and also tried changing the edge style to "Wedge" in preferences.yaml, but these all don't seem to have an effect on the final rendered visuals. Color palette does work though! I am using sleap v1.2.2 .

Thanks for your help!
Jensen

**Comment by talmo** [comment]
Hi @crazyhathello,

Thanks for the report. This is a feature we haven't quite gotten around to adding yet, but I agree would be very useful for generating better visualization clips. Tagging it as an enhancement for now and we'll update this thread when we start working on it.

Cheers,

Talmo
