### ISSUE TITLE
CLI for rendering video clip with instances

### ISSUE THREAD

**Issue by pinarkullu** [talmolab/sleap#718]
Hello,
Is there any Command line equivalent of  "Render Video Clip with Instances" GUI menu option?

Thank you for your help.

**Comment by talmo** [comment]
Hi @pinarkullu,

There is not a CLI equivalent but I agree that this would be a good feature to have. Tagging this as an enhancement.

In the meantime, you can achieve this by using a notebook or python script with the following:

```python
import sleap.io.visuals

sleap.io.visuals.save_labeled_video(
    filename="visualization.mp4",  # output filename
    labels=tracked_labels,  # sleap.Labels
    video=tracked_labels.video,  # sleap.Video
    frames=list(range(150)),  # list of frame indices
)
```

[Here's an example notebook](https://colab.research.google.com/drive/1wK_53ROHAhYtKVRSrG1OfYAwZSHeiH5e?usp=sharing) (scroll to the bottom).

Let me know if that works for you for now.

Cheers,

Talmo

**Comment by pinarkullu** [comment]
It works. Thank you

**Comment by davidasamy** [comment]
Hi @pinarkullu,

Wanted to let you know that this functionality has been added to the development version of SLEAP. If you would like to use it please install the [development version of SLEAP](https://sleap.ai/installation.html#conda-from-source) and use the [sleap-render](https://sleap.ai/develop/guides/cli.html#sleap-render) command.

Regards,
David

**Comment by roomrys** [comment]
Hi @pinarkullu,

The new release of SLEAP v1.2.4 is now available for [installation](https://sleap.ai/installation.html) and includes this fix.

Thanks,
Liezl
