### ISSUE TITLE
Exporting analysis HDF5 files for multi-video projects

### ISSUE THREAD

**Issue by ShivanshDave** [talmolab/sleap#729]
This is what I think is happening: Upon "File > Export Analysis H5..." SLEAP successfully saves the h5 file. No errors in terminal. But the issue is that SLEAP overwrites predictions from all videos on the same matrix (ie '/tracks') even though there's only one video open (and selected by default) in SLEAP GUI. -- Thus, h5 data is completely unusable, because it overwrites them as opposed to create different matrix for each video. (I think this might be the reason behind issue #611 that showed same frame-counts) 

Perhaps there is no error, and I am reading h5 file wrong. If so, please suggest how to access predictions from individual videos in the HDF5 file.  -- I tried using SLEAP 1.2.x on Windows10 to export, and reading hdf5 file in Matlab using the following command:
`tracks_matrix = h5read(h5file, '/tracks')`
`X_value = tracks_matrix(frame_ind, point_ind, 1)`
`Y_value = tracks_matrix(frame_ind, point_ind, 2)`

Ideally, it would be great to have two options in File menu, to export analysis from either the current video or all videos in the project.

**Comment by talmo** [comment]
Hi @ShivanshDave,

Yep, you're not doing anything wrong -- we generally keep the labeling project separate from the tracking, so the idea is that you generate individual `.slp` files for each session/video after you have a trained model that you're happy with. Consequently, the analysis HDF5 file is intended for single videos.

A convenient way of following this workflow is to use the [`sleap-track`](https://sleap.ai/guides/cli.html#sleap-track) CLI to run the tracking in batch for each video and create predictions files for each one.

We're planning on adding a new GUI element to make this a bit easier to work with (prototype in #494), but in the meantime one thing you can do is to automate this via a script like in #668.

@roomrys: I think we can simplify this into a smaller enhancement for the short term by just adding a menu (+CLI) option to export multiple HDF5 analysis files for multi-video SLP files. Even easier might be to just add this functionality to the existing Export Analysis HDF5 command with no interactivity for now.

**Comment by roomrys** [comment]
Hi @ShivanshDave ,

The new release of SLEAP v1.2.4 is now available for [installation](https://sleap.ai/installation.html) and includes this fix.

Thanks,
Liezl
