### ISSUE TITLE
Batch inference GUI

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#733]
We would like to add better front-end inference functionality to predict on multiple videos in the same project.

Goal: Be able to predict on each video in a project from the GUI.

MVP: Add an option to the target list in the Run inference GUI that says "all videos".

Related issues: #497, #668  -- see these for potential workarounds using the CLI.

Past efforts to build this functionality include PRs: #484, #494

**Comment by roomrys** [comment]
The new release of SLEAP v1.2.4 is now available for [installation](https://sleap.ai/installation.html) and includes an MVP for batch inference via the GUI.
