### ISSUE TITLE
SingleImageVideo does not support setting channels (RGB/grayscale)

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#735]
Problem: `SingleImageVideo` does not support the grayscale property correctly.

This will require adding this as an additional field for this backend, as well as ensuring backward compatibility for existing projects. (Deserialization might break when adding new fields to `attrs` classes.)

_Originally posted by @talmo in https://github.com/talmolab/sleap/issues/625#issuecomment-1109154125_

**Comment by roomrys** [comment]
Hi @laurelrr,

The new release of SLEAP v1.2.4 is now available for [installation](https://sleap.ai/installation.html) and includes this fix.

Thanks,
Liezl
