### ISSUE TITLE
Add Git installation instructions to docs

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#764]
We have instructions on opening the console, installing conda, and different installation methods, but not the `git` CLI. This would be a good complement to the "`conda` from source" method.

As a reference, see the instructions for M1 Mac installation -- it's step-by-step including how to install system-wide utilities analogous to `git` like `brew`.

The [git-scm](https://git-scm.com) Windows client is a bit intrusive of an install, but one option for Windows could be to have a PowerShell-based 1-liner like [chocolatey](https://chocolatey.org/install) has for their install method.

---

"I finally was able to install SLEAP from the source by installing "Git", otherwise there was an error telling me that "git" was not recognized. Beginners like me could experience the same, unfortunately the GUI is very important to us, thank you for improving it constantly! I stopped using DLC because of the GUI..."

_Originally posted by @ARTUR551 in https://github.com/talmolab/sleap/discussions/754#discussioncomment-2834277_

**Comment by roomrys** [comment]
I added a step to [conda from source installation](https://sleap.ai/installation.html#conda-from-source) where users first check their git version and if an error occurs, I direct them to [git-scm installation docs](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) which covers all installation methods for all OS's.
