### ISSUE TITLE
inference - many tracks for 2 instances

### ISSUE THREAD

**Issue by akshitasax** [talmolab/sleap#770]
Hi,

I work with 12 hour long video files. After running inference on the entire video, I usually get around 200 tracks broken up throughout the video. I usually have only 2 instances. Proofreading this would not be feasible. What can I do to help this? This happens when using default settings. I have also tried doing cull to target no. of instances, but just that didn't help much. 

I am also having an issue with the frequency of switched tracks. In some parts of the video it is almost as if the tracking is random. Can I do something to help this too?

Thank you

![Screenshot from 2022-05-31 18-03-48](https://user-images.githubusercontent.com/104799583/171314476-a1e83740-4003-41bc-ac55-432fa94c2ab5.png)

**Comment by roomrys** [comment]
Hi @akshitasax,

Have you tried using a Kalman Filter during inference? The [KF](https://sleap.ai/api/sleap.nn.tracker.kalman.html#:~:text=The%20Kalman%20filters,up%20the%20filters.) should help minimize switching. 

Also what [matching method](https://sleap.ai/develop/guides/proofreading.html#tracking-methods:~:text=Once%20SLEAP%20has,Hungarian%E2%80%9D%20matching.) are you using? Using Greedy matching will assign tracks based on the cost of matching in the current frame only while Hungarian matching will take into account the long-term cost across the all frames to predict on.

![image](https://user-images.githubusercontent.com/38435167/171465595-21418759-2f72-4423-89bf-70b576434ad7.png)
**Fig: Location of parameters in the Inference Pipeline that could help minimize track switching.**

Let us know if any of the above suggestions helped in your case and/or if you have more questions.

Tagging similar questions here: #714 ([helpful comment](https://github.com/talmolab/sleap/issues/714#issuecomment-1115460151)) and [How to get continuous tracking during inference](https://github.com/talmolab/sleap/discussions/741#discussion-4070525) (which ambiguously concludes that KF was the problem).

Thanks,
Liezl
