### ISSUE TITLE
predictor.predict error in Sleap_Realtime_Inference.ipynb with sleap of M1 Macs version

### ISSUE THREAD

**Issue by huangzj421** [talmolab/sleap#825]
# Bug description
Hi  threre,
Thanks for the sleap release, it's great and useful! I have installed sleap on my MacBook Pro (14-inch, 2021) successfully and tested sleap-label and sleap-track work well. But when I was trying to use the realtime inference function in this [Notebook](https://sleap.ai/notebooks/Interactive_and_realtime_inference.html), I found predictor.predict encounter an error during inference and I don't know why. Please help.

## Expected behaviour
In [9]: predictions = predictor.predict(imgs)
In [10]: predictions
Out[10]: Labels(labeled_frames=100, videos=1, skeletons=1, tracks=2)
## Actual behaviour
In [9]: predictions = predictor.predict(imgs)
In [10]: predictions
Out[10]: RuntimeError: Exception encountered when calling layer "top_down_inference_model" (type TopDownInferenceModel)...
Please check the screenshots below for details
## Your personal set up
- OS:
macOS 12.4
- Version(s):
SLEAP: 1.2.0a6
TensorFlow: 2.7.0
Numpy: 1.21.5
Python: 3.8.13
OS: macOS-12.4-arm64-arm-64bit
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
- SLEAP installation method:[M1 Macs](https://sleap.ai/installation.html#m1-macs)

## Screenshots
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/73161104/177158429-02059010-65e3-47fb-882e-d0d274890c52.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/73161104/177158586-f478e052-962d-40d4-acd4-f55934c8a7f6.png">
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/73161104/177158671-284767ab-98eb-45f5-820b-9d86e9b9232f.png">

## How to reproduce

1. Install sleap following the [process](https://sleap.ai/installation.html#m1-macs)
2. Run the [Notebook](https://sleap.ai/notebooks/Interactive_and_realtime_inference.html)

**Comment by talmo** [comment]
Hi @huangzj421,

Sorry for the super long delay! This looks to be an issue where you're trying to track using just the centroid model. Top-down approach requires both the centroid and a centered_instance model. You provide both to create the predictor like `sleap.load_model(["path/to/centroid_model", "path/to/centered_instance_model"])`.

We have another issue open that will hopefully help to make this a clearer error message (#885).

Closing this for now but please feel free to let us know if you're running into any other issues.

Cheers,

Talmo
