### ISSUE TITLE
Assigning user instances to tracks unlinks them from predicted

### ISSUE THREAD

**Issue by talmo** [talmolab/sleap#866]
# Bug description

## Expected behaviour

Setting the track on a user instance that was created from a predicted instance causes predicted instances to re-appear.

## Actual behaviour

Setting the track on a user instance that was created from a predicted instance should not cause predicted instances to appear.

## Screenshots

User labeled instances created from predictions:
![image](https://user-images.githubusercontent.com/3187454/181142149-b1a9226a-1399-4302-82a5-0701c0c8afd1.png)

After assigning one instance to a track:
![image](https://user-images.githubusercontent.com/3187454/181142374-68e7217f-b7e8-40cc-a723-312cec913ef9.png)

Instances panel shows all instances:
![image](https://user-images.githubusercontent.com/3187454/181142430-f4162068-3cc8-4d0a-88d8-aafac827ce46.png)

## How to reproduce

1. Create a user instance from a predicted instance.
2. Assign the user instance to a track.
3. Predicted instance re-appears.

**Comment by roomrys** [comment]
This issue has been resolved in the new release - install SLEAP v1.2.7 [here](https://sleap.ai/installation.html#conda-package).
