### ISSUE TITLE
Node trails don't update during proofreading

### ISSUE THREAD

**Issue by olinesn** [talmolab/sleap#897]
When proofreading a .slp file, I'll often update the position of the subject's nose, which has a higher error rate than other nodes. I also leave the Trail Length at 10 to catch mislabelled nodes wile scrubbing through the video.

However, the Trail doesn't update when the node position is corrected. A fix for this would be for the plotted Trail to reflect changes in the proofread data (which is already reflected in the exported h5 files).

Thanks!

![image (9)](https://user-images.githubusercontent.com/69451171/183495681-47c85229-cc48-4028-9ac9-ea3efd1838ab.png)

**Comment by roomrys** [comment]
## Relevant Code
1. Method to load overlays inside `MainWindow` class.
https://github.com/talmolab/sleap/blob/2efae3d96e7c843a52b855c37be96fea9c6e2725/sleap/gui/app.py#L1139-L1179

2. Methods to plot overlays inside `TrackTrailOverlay` class.
https://github.com/talmolab/sleap/blob/2efae3d96e7c843a52b855c37be96fea9c6e2725/sleap/gui/overlays/tracks.py#L122-L170

3. Function where `TrackTrailOverlay.add_to_scene` is called
https://github.com/talmolab/sleap/blob/2efae3d96e7c843a52b855c37be96fea9c6e2725/sleap/gui/app.py#L1331-L1355

**Comment by roomrys** [comment]
This issue has been resolved in the new release - install SLEAP v1.2.7 [here](https://sleap.ai/installation.html#conda-package).

**Comment by olinesn** [comment]
Hi Liezl @roomrys,

Thanks so much for pushing a fix for this. I'm seeing some strange behavior in 1.2.7, figured I'd let you know.

https://user-images.githubusercontent.com/69451171/189764685-6ef413a0-c090-447f-ab15-19254f1c0bfb.mp4


It looks like while the trails are being updated with the new information, the old nodes aren't being deleted. This seems to result in a 'zig-zag' pattern where the trail vector is based on alternating inferred/corrected nodes. I think the old nodes are therefore not being deleted, and a trail-length of 10 shows 5 corrected nodes and 5 inferred nodes.

Hope this video helps describe the behavior.

Best,
Stefan

**Comment by roomrys** [comment]
Oof, thanks for the heads up Stefan @olinesn.

## Relevant Code
Here we have the function `TrackTrailOverlay.add_to_scene` 
https://github.com/talmolab/sleap/blob/b2cd605a2a87c59ac91058b7065ce904a9402ad3/sleap/gui/overlays/tracks.py#L122-L170
which uses `TrackTrailOverlay.get_track_trails` to get the data needed to draw the track trail
https://github.com/talmolab/sleap/blob/b2cd605a2a87c59ac91058b7065ce904a9402ad3/sleap/gui/overlays/tracks.py#L40-L85
