### ISSUE TITLE
from sleap.nn.inference import TopdownPredictor Error

### ISSUE THREAD

**Issue by Deep-learning999** [talmolab/sleap#899]
from sleap.nn.inference import TopdownPredictor,Tracker

predictor = TopdownPredictor.from_trained_models(
centroid_model_path="C:/Users/designlion/Documents/openvino_notebooks/notebooks/0000001sleap-mit-tutorial/sleap-mit-tutorial-master/models/baseline_model.centroids",
confmap_model_path="C:/Users/designlion/Documents/openvino_notebooks/notebooks/0000001sleap-mit-tutorial/sleap-mit-tutorial-master/models/baseline_model.topdown",
)
predictor.tracker = Tracker.make_tracker_by_name(tracker="simple")

ImportError Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 from sleap.nn.inference import TopdownPredictor,Tracker
3 predictor = TopdownPredictor.from_trained_models(
4 centroid_model_path="C:/Users/designlion/Documents/openvino_notebooks/notebooks/0000001sleap-mit-tutorial/sleap-mit-tutorial-master/models/baseline_model.centroids",
5 confmap_model_path="C:/Users/designlion/Documents/openvino_notebooks/notebooks/0000001sleap-mit-tutorial/sleap-mit-tutorial-master/models/baseline_model.topdown",
6 )
7 predictor.tracker = Tracker.make_tracker_by_name(tracker="simple")

ImportError: cannot import name 'TopdownPredictor' from 'sleap.nn.inference' (E:\anaconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py)

**Comment by talmo** [comment]
Hey @Deep-learning999,

This is from a tutorial notebook for an older version of SLEAP -- try `from sleap.nn.inference import TopDownPredictor`, or better yet, see [this notebook](https://sleap.ai/notebooks/Interactive_and_realtime_inference.html) for examples using the newer API.

Cheers,

Talmo
