### ISSUE TITLE
Guidelines for Contributing Don't Point to Correct Place

### ISSUE THREAD

**Issue by jmdelahanty** [talmolab/sleap#909]
# Bug description

When going through the outside contributor guidelines, I noticed that the link doesn't seem to point to a location that exists! It just takes you to the repo's main page.

## Expected behaviour

Link should point to the contributing markdown I think.

## Actual behaviour

It looks like the link is currently configured to go to a wiki that might not exist anymore, or at least I can't find it. So you get redirected to the repo's homepage.

## Your personal set up

Just clicking around online through the repo here.

- OS:
N/A
- Version(s):
N/A
- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
N/A

## Screenshots

N/A

## How to reproduce

1. Make a PR
2. Click on the "Review the [guidelines for contributing](https://github.com/talmolab/sleap/wiki/Developer-Guide) to this repository" link (included here). Seems like it's supposed to point [here](https://github.com/talmolab/sleap/blob/main/docs/CONTRIBUTING.md).

**Comment by roomrys** [comment]
Hi @jmdelahanty,

The link has been updated.

Thanks,
Liezl
